### ISSUE TITLE
Feature request: Enter distances to several known stars

### ISSUE THREAD

**Issue by Harbinger73** [EDDiscovery/EDDiscovery#1]
I like the way you can enter distance measurements between the last star you've visited and submit the data to EDSC but unless you're going to jump back and forth between the star with no coordinates and those with known coordinates it's not terribly effective a means of mapping the coordinates of unknown stars.
EDDiscovery could really do with a feature to manually enter distances to 5+ systems of known coordinates in a way similar to what is possible on the EDSC website.

**Comment by 0xyg3nist** [comment]
Trading Data went hard with the OCR... time to start getting the OCR going for the navigation panel  That way it will automatically enter all the start systems it sees there (of more than 0.5ly away)

**Comment by Majkl578** [comment]
Hi,
preliminary support for this is in my [trilateration branch](https://github.com/Majkl578/EDDiscovery/commits/trilateration), reusing trilateration math used by [ed-systems/entry.html](https://github.com/SteveHodge/ed-systems/blob/master/entry.html). There is still some work left though.
In meantime you can use this site: http://robert.astronet.se/Elite/ed-systems/entry.html
![trilateration](https://cloud.githubusercontent.com/assets/144181/8246570/210944b2-1641-11e5-99c0-c664fedd1c46.png)


@0xyg3nist: I'm afraid the data from Navigation panel are not precise enough. Any distance over 10.00Ly is listed with only one decimal place which is not enough (IIRC). So it would be applicable only to the systems below 10.00Ly...

**Comment by finwen** [comment]
Looks promissing. 

 Prefered place to get distance is from the Galaxy map. It has always 2 decimals.

**Comment by 0xyg3nist** [comment]
It's not the decimal places per se. The accuracy is a function of the number of significant figures in the distance, and the accuracy of the sin function. 
The math will sort itself out, if you can data mine ten times as much data out of ED because it's twenty-times easier to get it from a half decent OCR. 
If we n00bs had an application which dragged out the screenshots and dumped them in separate folders: Galaxy map screenshots (auto cropped to the star info), commodity screens (also semi-cropped?), navigational panel screenshots (cropped), and then in a seperate process scan each folder and grab the simple data automatically, keep a repository of data the needs verification until it's two hours old and then dump it... I can't code beyond the pseudo code I learnt fifteen years ago. 
Get ten locations on a star instead of five from those around it, some with some luck some are galaxy map four or five significant-figure  measurements from there. The confidence factor will deal with the need to improve on those that are only 3 significant figures and beyond the sin functions' accuracy.

**Comment by Majkl578** [comment]
@0xyg3nist: I agree it would be nice to have much more data automatically, it's a nice idea. But I'm still not sure what impact it would have if we got most of the systems with only one decimal place. I suppose it'd at least require (a lot) more system distances for trilateration (minimum is 5 now). I believe @SteveHodge (the author of ed-systems) could tell you more about this.


And here's an update for this issue:
![Trilateration](https://cloud.githubusercontent.com/assets/144181/8265756/fcc309a8-1708-11e5-9f87-245410a41ab3.png)

**Comment by SteveHodge** [comment]
I believe the nav panel calculates the distance from your ship position and not the primary star. That makes it quite difficult to use as the nav panel distances don't always correspond to the galaxy map distances even when the distance is less than 10 Ly and the nav panel shows 2 decimal places.

**Comment by Majkl578** [comment]
Closing, trilateration was implemented in 2.3.0.0.
