### ISSUE TITLE
Asteroid Belt is not displaying in right place in system

### ISSUE THREAD

**Issue by vashts6583** [EDDiscovery/EDDiscovery#1018]
Just scanned a system with a belt that's after P3, but on the Scan view, it shows Main Star, A Belt, 1, 2, 3 (etc.)  We do know from scanning the star that A Belt has inner/outer radii in Ls, and each scanned body has a distance from drop.  Is there a way to place the newly scanned planets with an arrival point less than the inner radius for the belt close to the star?
![edd_scans](https://cloud.githubusercontent.com/assets/15353221/25368140/81621b74-2948-11e7-8720-0171a500772a.png)
![sys_view](https://cloud.githubusercontent.com/assets/15353221/25368139/8161e492-2948-11e7-8d16-7b104ae2f737.png)

**Comment by klightspeed** [comment]
This might be doable provided the planet in question isn't co-orbital with another planet (as planet 4/5 and 6/7 are in your screenshot.  Unfortunately the only way to tell if a planet is co-orbital with another is if both planets' orbital periods are the same.  There is nothing to scan to tell the program what the semi-major axis of the binary pair is around the star (or barycentre in a multi-star system), so at best it can only go by inner planets that are inside the radius of the belt.

Note also that belts are properties of the star, and are not presented as bodies in scans.

**Comment by klightspeed** [comment]
Looking at the code, this would require separating the rings and belts out to their own objects in the planet tree, and inserting them either before the innermost planet with a larger semi-major axis (which would put them out past planet 7 in your case) or after the outermost planet with a smaller keplerian semi-major axis (which would put it just after planet 3 in your case).

At the moment, rings are always drawn immediately below the body, and belts are always drawn immediately right of the body, since in both cases they are properties on the body scan and are thus drawn with the node to which they belong.

**Comment by vashts6583** [comment]
I think what'd probably work "best" would be the "after the outermost planet with a smaller keplerian semi-major axis" if this is something you want to try and address.

Thank you for taking a look at this.

**Comment by iainross** [comment]
"after the outermost planet with a smaller keplerian semi-major axis" works in this instance because the inner three planets are orbiting on their own.  If they were co-orbiting as a trinary set then the position of the rings would end up out past the 7th planet again.

Distance from arrival should work for single star systems.  For multiple star systems you could try assuing that you can roughly draw a right angled triangle and get the approximate distance from a second star for its planets where (distance from arrival for 2nd star)^2 + (distance from 2nd star to planet)^2 = (distance from arrival for planet)^2 - without looking at some system data I'm not sure how reliably that would work but it might be close enough.  

If it does someone could do it that way but basing it on the semi major axes we get given is going to put the rings in weird and arbitrary positions for a lot of systems.

**Comment by robbyxp1** [comment]
Frontier do not supply all the data required to do a perfect copy of their screen, as noted above.
I would suggest we leave as is

**Comment by klightspeed** [comment]
> Distance from arrival should work for single star systems.

i.e. if the semi-major axis is not keplerian (i.e. `((SemiMajorAxis ** 3) / (OrbitalPeriod ** 2))` is not within e.g. 2% of `Star.StellarMass * 3.361e18`), and it's a single-star system, then use the distance from arrival? 

> For multiple star systems you could try assuing that you can roughly draw a right angled triangle and get the approximate distance from a second star for its planets where (distance from arrival for 2nd star)^2 + (distance from 2nd star to planet)^2 = (distance from arrival for planet)^2 - without looking at some system data I'm not sure how reliably that would work but it might be close enough.

That assumes that the line between the two stars and the line to the planet are at right angles.  The planet's distance from arrival can be up to `+/- SemiMajorAxis * 2` from the star's distance from arrival, depending on the planet's position in its orbit at whatever epoch the distance from arrival is calculated.

**Comment by iainross** [comment]
I'm aware that's an assumption Sir Humphrey would definitely call "brave", but it might be close enough....

Mostly I do agree with Robby that it's not worth the effort it would take to get it right most of the time and I don't think that we have enough information to guarantee we're getting it right all of the time however carefully we analyse it so we should really leave it as is unless FDev upgrade what's in the journal.

**Comment by robbyxp1** [comment]
Closing, do not have enough info to make a correct guess
