### ISSUE TITLE
Systems known to EDSM showing as "not known to EDSM" when entered into Routes/Expeditions planner

### ISSUE THREAD

**Issue by ParadoxBomb** [EDDiscovery/EDDiscovery#1029]
EDDiscovery Version 7.0.3.0
OS: Windows 10 64-bit

To reproduce, double-click on the "System Name" box to begin typing a system (for example, "Sol"). Press Enter to go to the next cell. If reproduced, the system should be blue and have a warning star next to it like so: [http://i.imgur.com/6sAXMIE.png](http://i.imgur.com/6sAXMIE.png)

It seems that when selecting the system from the dropdown, this problem does not occur. [http://i.imgur.com/oc5Q6BQ.png](http://i.imgur.com/oc5Q6BQ.png)

Edit: fixed links to actually point to the links they should be pointing to.

**Comment by phroggster** [comment]
This is an issue with the UserControl that is used for auto-complete, both here and on other tabs. It doesn't interpret enter as "choose the selected entry" like it needs to. It also behaves badly if one uses the keyboard to select text (CTRL+A, SHIFT+Home, etc), since it interprets any keyboard input as text and just starts up another search.

The fix is a huge headache, and involves manually processing every non-text character to perform text selections and submission.

**Comment by robbyxp1** [comment]
appears fixed

**Comment by phroggster** [comment]
Yeah, it appears to have been resolved with the release of EDD 8.3, although I never determined where/why. To confirm, there was a different issue in EDD where certain systems (typically a block of ~10k) were getting dropped from the `systemWithCoordinates.json` import and never making it into our database. I've had a few syncs where Sagittarius A* was missing, as well as Beagle Point, and these were shown as unknown even when loading the the hard-coded expeditions! *That bug* has been fixed.

`AutoCompleteTextBox`/`AutoCompleteDGV` still have some faults, and in some cases don't behave the way they should, but they're getting better every day.
