### ISSUE TITLE
Track value of discovery scans

### ISSUE THREAD

**Issue by JJ12880** [EDDiscovery/EDDiscovery#1115]
Seeing that there is an existing mechanism that adds the estimated value of the scanned body to the journal, could those values be summed and kept as a running total, so that the player would have a rough estimate of the value of their scan data?  This SHOULD work, assuming there is a way to determine when a user sells their scan data.

**Comment by klightspeed** [comment]
The estimated value is calculated at runtime, and is not stored in the journal.  The stats panel includes an estimated scan value in each time period (day, week, month and all-time in summary mode) taken from these estimates.

As the `SellExplorationData` event only includes systems, and not bodies, it is not possible to determine precisely which scans have been sold.

It might be possible to add a line in the stats panel for the value of all sold exploration data in the journals.

**Comment by tonkepen100** [comment]
I think it would be sensational to put two values:

1,. In S-Panel, a new column, that says the approximate value of the body scanned.

Example:

![captura](https://user-images.githubusercontent.com/4571086/28237996-adb3b894-694a-11e7-8072-294ac387f3eb.PNG)

2.- A cell where it tells us the approximate sum total of the bodies scanned during a session, or during an exploration.

Example:

![capterra](https://user-images.githubusercontent.com/4571086/28237998-b4fa5342-694a-11e7-9b2e-d2ceb16c95e3.PNG)

Or

![captuasdra](https://user-images.githubusercontent.com/4571086/28238000-be17d1de-694a-11e7-827c-03482bb3e80f.PNG)

Thanks and sorry for my English, it's very bad

**Comment by klightspeed** [comment]
This is where being able to customize the columns in the summary panel and/or travel history would probably be helpful.

**Comment by JJ12880** [comment]
Given that you cant tell for sure what was sold, could you modify my original suggestion to keep a total of the guesstimated value of the bodies scanned after last docking?  It may not represent the total value of the data held, but at least the number calculated could accurately represent what it claims to represent.

**Comment by tonkepen100** [comment]
------- _This is where being able to customize the columns in the summary panel and/or travel history would probably be helpful._ ------


First of all to ask for forgiveness to JJ12880, since the thread is his and asks for another topic other than mine, I am sorry but my English is very bad, and to see exploration, I rushed like a bull, to ask for my proposition. Sorry if I'm mixing songs.

The theme is that on all sides we have the approximate values ​​of scans, in statistics, in spanel when the data explored, etc. etc.

But the truth is that in the game you do not know the value of this scan, so you have to go to statistics to see those values, so I think it would be logical for the user to see the scan (in Spanel the value scanned); And on the other hand the most important would be. And I'm going to set an example so that I get better, I'm going to make an exploration, well, that interests me ?, since I know more or less how much I have added in this exploration, right? Well that information, I think would be important, Following the example, I take 3 weeks of exploration and I see I carry 7000000 of credits and I say, come home, I already worth.

So I repeat I would put a column in spanel with the value of the body scanned, and on another side the total sum of the period of my exploration, as you have to add the partial statistics in each day, since not necessarily Coincides with departure and arrival.

In itself I consider it easy to do it since the values ​​of scans are already implemented.

Thanks again for your attention, which has always been magnificant.

**Comment by iainross** [comment]
There's a Statistics panel which will show you, amongst other things, the total estimated value of scans over an array of periods - one of which is since you last docked, so there's your current trip total.

**Comment by tonkepen100** [comment]
I did not forgive what I would like, is to know within S.panel in another column the estimated value of explored body, without having to see it in a huge window that comes out every time I do. And comes out at the bottom.

And also to see if said body scanned, according to EDSM, is the first to discover it.


For example, instead of defining within it, how much of my goal is, since it tells me at the top of that popup and I really do not care. For that

I think it's simple is to put a new column inside S.Panel and define whether it is desired or not.

Likewise and since we have, or we can define if we want connection with EDSM, why we can not see inside said panel if it is defined as discovered ?.

EDSM is giving such data, and Discovery in its options, points to if you want to confront said data, so the data provided by EDSM, determines if that star body is discovered by you, just as for example Market connector says so.

But even for a long time and only with a simple script in one of my beaglebones mine, I have my own table, which EDSM sends me, and automatically tells me if it is discovered or not.

See:

WEB: http://tonique.ovh
GALLERY: http://tonique.ovh gallery

As you will see I put it green, in a simple table to define whether it is discovered or not, or red if it is not.

More even the unification of S-panel and Route tracker is necessary. As long as the ROUTE tab is cleaned.

(As always sorry for my English, please enterder that I can not express myself as I would really like, sorry, I promise that when I am born again I learn Spanish again.)

@iainross  Oleeeee

**Comment by inktomi** [comment]
Another way this could work is by creating a new tab/export in EDDiscovery - "Expedition Mode". An explorer would set the "Start Jump" event that marks the beginning of their trip, and then values would be tallied from then until they mark the expedition complete. This would allow people to view their events just for their current trip, estimated values, materials, etc. 

How many M type stars have I scanned on this trip? 
How many tons of fuel have I scooped? 
What kind of money might I expect when I return?

I think this would add a lot to the program, and us explorers would likely find it very useful!

**Comment by Lensman-86** [comment]
Inktomi has listed some great ideas, which I feel would also benefit your application, but in addition to stars, if it could be expanded to planet types, that would be a huge help as well.

While i can understand some of your reservations about this feature, and it's potential to cause a bit of grumbling, in defense of the idea, even an estimated value for scanned objects could be used, It would be of great help to explorers, and by reporting that these are estimated values, could also save you a bit of a headache over values not being exact. You could use a widely-used source, such as CMDR Fru's 2.3 Exploration Payout Guide as a reference, which might save you a bit of time in having to figure out values for each type of scanned object.

Thanks for reading, and i do hope you can add this feature.

**Comment by wokket** [comment]
I'm currently adding the total system scan value to the Scan panel as part of #1185, per image below.

Between this feature and the changes already included in #1294 I think this addresses the original request sufficiently to close this issue?  

![image](https://user-images.githubusercontent.com/3802829/30998137-ce814a68-a50f-11e7-954f-06a71b3dfc03.png)

**Comment by inktomi** [comment]
That looks great! Thank you for working on this for us!
