### ISSUE TITLE
"Gamma Andromedae B" in Almach is not being sent or synced correctly

### ISSUE THREAD

**Issue by panzertard** [EDDiscovery/EDDiscovery#1176]
I was running v.8.1.5 Portable edition at the time.
1. Jumped into Almach.
2. Scanned first star, it happened to be "Gamma Andromedae B"
3. Scanned the rest.
EDSM and EDDB have no trace of "Gamma Andromedae B" in Almach.
https://www.edsm.net/en/system/bodies/id/1929964/name/Almach
https://eddb.io/system/bodies/194502
https://ross.eddb.io/eddn/log?parsing_result=&parsing_result_detail=&header_software_name=&schema=&schema_main_group=&schema_sub_group=&system_id=194502&station_id=&body_id=

From the journal, the events happened in this order:
```
{ "timestamp":"2017-08-05T23:50:16Z", "event":"StartJump", "JumpType":"Hyperspace", "StarSystem":"Almach", "StarClass":"K" }

{ "timestamp":"2017-08-05T23:50:34Z", "event":"FSDJump", "StarSystem":"Almach", "StarPos":[-228.000,-110.656,-248.500], "SystemAllegiance":"", "SystemEconomy":"$economy_None;", "SystemEconomy_Localised":"None", "SystemGovernment":"$government_None;", "SystemGovernment_Localised":"None", "SystemSecurity":"$SYSTEM_SECURITY_low;", "SystemSecurity_Localised":"Low Security", "JumpDist":19.536, "FuelUsed":2.632070, "FuelLevel":51.323452 }

{ "timestamp":"2017-08-05T23:50:56Z", "event":"Scan", "BodyName":"Gamma Andromedae B", "DistanceFromArrivalLS":0.000000, "StarType":"B", "StellarMass":5.832031, "Radius":2088834560.000000, "AbsoluteMagnitude":-2.304291, "Age_MY":350, "SurfaceTemperature":17234.000000, "SemiMajorAxis":47085682688.000000, "Eccentricity":0.038773, "OrbitalInclination":53.712009, "Periapsis":299.751343, "OrbitalPeriod":64234916.000000, "RotationPeriod":88915.578125, "AxialTilt":0.224622 }

{ "timestamp":"2017-08-05T23:51:32Z", "event":"Scan", "BodyName":"Almach", "DistanceFromArrivalLS":1457.942383, "StarType":"K_OrangeGiant", "StellarMass":0.683594, "Radius":55639998464.000000, "AbsoluteMagnitude":-3.083420, "Age_MY":7348, "SurfaceTemperature":3998.000000, "SemiMajorAxis":401708253184.000000, "Eccentricity":0.038773, "OrbitalInclination":53.712009, "Periapsis":119.751335, "OrbitalPeriod":64234916.000000, "RotationPeriod":26039656.000000, "AxialTilt":-0.202368 }

{ "timestamp":"2017-08-05T23:58:56Z", "event":"Scan", "BodyName":"Almach AB 1", "DistanceFromArrivalLS":22027.472656, "TidalLock":false, "TerraformState":"", "PlanetClass":"Sudarsky class III gas giant", "Atmosphere":"", "AtmosphereComposition":[ { "Name":"Hydrogen", "Percent":73.513550 }, { "Name":"Helium", "Percent":26.486444 } ], "Volcanism":"", "MassEM":24.107784, "Radius":22907976.000000, "SurfaceGravity":18.310209, "SurfaceTemperature":304.309998, "SurfacePressure":0.000000, "Landable":false, "SemiMajorAxis":4576919420928.000000, "Eccentricity":0.446196, "OrbitalInclination":76.852470, "Periapsis":266.049194, "OrbitalPeriod":2091982720.000000, "RotationPeriod":112677.015625, "AxialTilt":0.460129 }
```

From the \Logs
```
[2017-08-06 01:50:16Z] New entry 05.08.2017 23:50:16 StartJump
[2017-08-06 01:50:34Z] New entry 05.08.2017 23:50:34 FSDJump
[2017-08-06 01:50:34Z] Arrived at system: Almach 1:th visit.
[2017-08-06 01:50:34Z] Update sync flag ID 47858 with 1
[2017-08-06 01:50:34Z] Update sync flag ID 47858 with 3
[2017-08-06 01:50:56Z] New entry 05.08.2017 23:50:56 Scan
[2017-08-06 01:51:21Z] New entry 05.08.2017 23:51:20 FuelScoop
[2017-08-06 01:51:32Z] New entry 05.08.2017 23:51:32 Scan
[2017-08-06 01:51:32Z] Update sync flag ID 47861 with 2
[2017-08-06 01:55:55Z] New entry 05.08.2017 23:55:55 USSDrop
[2017-08-06 01:55:56Z] New entry 05.08.2017 23:55:56 SupercruiseExit
[2017-08-06 01:56:30Z] New entry 05.08.2017 23:56:30 StartJump
[2017-08-06 01:56:35Z] New entry 05.08.2017 23:56:35 SupercruiseEntry
[2017-08-06 01:58:56Z] New entry 05.08.2017 23:58:56 Scan
[2017-08-06 01:58:56Z] Update sync flag ID 47866 with 2

```

**Comment by panzertard** [comment]
Note, I'm now runnign 8.1.6 Portable.
I just discovered the feature on the Admin-menu for "Send unsynced EDDN events", there was a bit of backlog here. I'll be watching to see whether Almach shows up for sync.

**Comment by klightspeed** [comment]
To automatically send bodies to EDDN, you need to check `Send to EDDN` in your commander's profile in EDDiscovery.

Does the system show up properly in the system map in EDDiscovery? (S Panel -> Scan)

It should show Almach as the primary, Gamma Andromedae B as the secondary, and Almach AB 1 orbiting their combined barycenter.

**Comment by panzertard** [comment]
EDSM Name & API Key as well as "Sync to EDSM" are enabled.
The unsynced events may have been scans I did _from 2.1 onwards and to the point where I installed EDDiscovery_ for the first time.

Agree that "**Gamma Andromedae B**" should have been sent as part of Almach, where Almach A is primary.
But the data has not reached the EDSM / EDDB networks.

**Comment by klightspeed** [comment]
What does the scan panel in EDDiscovery show for the system?

**Comment by panzertard** [comment]
Here's a image:
![eddiscovery-almach](https://user-images.githubusercontent.com/15065663/29004888-8b3a647a-7acf-11e7-9220-c2b561622cf1.png)

**Comment by klightspeed** [comment]
What happens if you click Refresh, then select the scan again?

This is an issue with star systems where the brightest star (the A star) is not the most massive star in the system (where you drop out from Hyperspace) and where the secondary star's name has nothing in common with the system name - until the primary star (Almach in this case) is scanned, EDDiscovery is not able to determine if the secondary star (Gamma Andromedae B in this case) belongs in the system (the Scan event does not contain the system the body is in).  Once the primary star has been scanned (or its scan event has been read), its data is cached in memory, and should apply once the travel history is refreshed.

Perhaps we should re-evaluate all of the scan events for the system once the primary star has been scanned.

**Comment by panzertard** [comment]
The journal shows that I scanned. I cannot rescan something I've already scanned.
However, we have the journal to reproduce the problem (1'st post).

As for solution to the conundrum in code:
- On scan result, use last FSDJump.system
- if FSDjump.system = null, use old algorithm.

**Comment by klightspeed** [comment]
Please click Refresh, then select the scan again and post what it shows.

When the primary star is scanned first, it shows:
![image](https://user-images.githubusercontent.com/147116/29005167-a59f89d2-7b18-11e7-9070-1375f567e6ed.png)

As an example of a system where the secondary star was scanned first:
Before refresh:
![image](https://user-images.githubusercontent.com/147116/29005216-78a41456-7b19-11e7-9e18-3ba2ff2bd7e6.png)

After refresh:
![image](https://user-images.githubusercontent.com/147116/29005223-901ac1ac-7b19-11e7-8bb8-c73ac2dddf98.png)

The reason we don't just trust the scan to be in the same system as the last FSDJump is because sometimes the scan journal entry will be delayed until after jumping to the next system - see https://github.com/EDDiscovery/EDDiscovery/issues/534

**Comment by panzertard** [comment]
As in 1. the Refresh button up right corner
2. and then "Rescan all Journals" from the Menu?
Ok, at least that's what I did, this is the result:
![eddiscovery-almach2](https://user-images.githubusercontent.com/15065663/29005306-7955bbfc-7ad8-11e7-94ef-1d7b9345ba11.png)

**Comment by klightspeed** [comment]
Rescan all Journals is used for if a previous version missed an event.  It is not necessary when refreshing the history display.

I took a commander I have in the Bubble out to that system and deliberately scanned the primary star first.

**Comment by panzertard** [comment]
Brilliant, at least it's recorded properly now.
I'm just trying to be diligent that we have a good data-quality of what's being delivered to the network. we're all consuming this data later. :)
