### ISSUE TITLE
Cannot maximize EDD window

### ISSUE THREAD

**Issue by vashts6583** [EDDiscovery/EDDiscovery#1187]
When using 8.1.5.0 I could double-click on the top bar of the EDD window to maximize the application.  In 8.2.1.0 pre-release, double-clicking the top of the EDD window appears to do nothing.

Steps to reproduce:
1. Open EDD and change window size to be smaller than the size of your monitor.
2. Double-click the main application window just to the right of the version number.

Expected Results:
2. EDD application window maximizes to the size of the current monitor.

Actual Results:
2. EDD application window size does not change.

**Comment by phroggster** [comment]
Worth noting that this issue should only be seen when the theme has removed the standard window frame.

I meant to mention this previously, but try double-clicking in the area to the directly to the right of the main menu strip. The area higher up than this doesn't seem to respond appropriately, and the area below it isn't considered the caption area.

Also, there seems to be an issue if the main form starts maximized (because it was closed while maximized and wants to return to it's last position), whereby it doesn't have prior non-maximized `RestoreBounds` to restore to. Un-maximizing this window will result in a programatically  non-maximized window that still appears to be maximized.

**Comment by vashts6583** [comment]
I figured out that you meant the tab strip.  This is very odd, but I'm ok knowing this.  Thank you for your response :)

**Comment by phroggster** [comment]
My pleasure, and I edited the misattributed menu strip in my comment to be tab strip, as you are correct. Whenever a7c9973 gets into a release (8.3 or so?), you should find that the clickable area is a whole lot larger than just the unused tab strip rectangle, including: unused menu strip, version label, update available/loading/closing/misc message textbox, and anything else that gets decided to be included.
