### ISSUE TITLE
EDD 8.2.3.0 Fatal Error While Initializing

### ISSUE THREAD

**Issue by QohenLeth** [EDDiscovery/EDDiscovery#1206]
Fatal exception while Initializing.

```
==== BEGIN ====
System.Data.SQLite.SQLiteException (0x80004005): unable to open database file
   à System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   à System.Data.SQLite.SQLiteConnection.Open()
   à EliteDangerousCore.DB.SQLiteConnectionED`1..ctor(Nullable`1 maindb, Boolean utctimeindicator, Boolean initializing, Boolean shortlived) dans V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteConnectionED.cs:ligne 147
   à EliteDangerousCore.DB.SQLiteConnectionUser.<>c.<Initialize>b__4_0() dans V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteConnectionUser.cs:ligne 45
   à EliteDangerousCore.DB.SQLiteConnectionED`1.InitializeIfNeeded(Action initializer) dans V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteConnectionED.cs:ligne 87
   à EDDiscovery.EDDiscoveryController.InitializeDatabases() dans V:\RobertW\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:ligne 320
   à EDDiscovery.EDDiscoveryController.Initialize(Action`1 msg) dans V:\RobertW\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:ligne 102
   à EDDiscovery.EDDApplicationContext.initTimer_Tick(Object sender, EventArgs e) dans V:\RobertW\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:ligne 128
===== END =====
```

EDD 8.2.3.0 Portable, first launch ever.
Win10 Pro (up-to-date)
AMD FX-8350 8x4GHz
12GB DDR3
Samsung 850 Evo 250GB SSD

**Comment by klightspeed** [comment]
I wonder if it's creating the data directory?

**Comment by QohenLeth** [comment]
Possible it doesn't. I'm having a few security issues with this brand new Win10; I installed the portable version on another drive and it runs fine.

**Comment by klightspeed** [comment]
If you type `%LOCALAPPDATA%` in your File Explorer address bar, does it take you to `AppData\Local` in your profile directory.

In that directory, does `EDDiscovery` exist as a directory?

If it doesn't, are you able to create it?

**Comment by QohenLeth** [comment]
It didn't exist, but I could create it.

**Comment by klightspeed** [comment]
Do you have an `options.txt` in your program directory?

**Comment by phroggster** [comment]
Pardon, but I think that klightspeed missed the fact that you were using the portable version. This version attempts to store data elsewhere, under a "Data" subfolder alongside wherever the portable EDDiscovery.exe exists at, instead of under `%LocalAppData%`.

Did the application create a "Data" folder inside of its folder? If not, are you able to manually create such a folder there? Lastly, the prior comment regarding `options.txt`, does that file exist alongside EDDiscovery.exe, and what are its contents, if so?

**Comment by QohenLeth** [comment]
There is a Data folder, which contains a Log folder, both of them empty, and there is no option.txt file in the .exe directory.

**Comment by klightspeed** [comment]
Where is the portable version installed?

If it's installed under `Program Files`, then Windows will redirect any writes by the program, and this could be causing problems for the SQLite library.  If it's installed in another directory, make sure you have full permissions to the directory.

**Comment by QohenLeth** [comment]
It was simply put on the desktop; part of User/My Docs, so I have full rights (and I checked twice).

**Comment by klightspeed** [comment]
Would you please be able to use ProcessMonitor (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to capture the system calls executed by EDDiscovery:
* Start Process Monitor
* Start EDDiscovery
* When EDDIscovery crashes due to that database problem, stop capture by pressing <kbd>Ctrl</kbd>+<kbd>E</kbd> or clicking the magnifying glass ![image](https://user-images.githubusercontent.com/147116/29743499-e4296a6a-8ad6-11e7-9eea-64fdacb38442.png)
* Right-click a `SUCCESS` value in the `Result` column, and click `Exclude 'SUCCESS'`
* Right-click a `CreateFile` event, and click `Include` -> `Event Class`
* Press <kbd>Ctrl</kbd>+<kbd>F</kbd> and search for `mscoree.dll`
* Right-click the `EDDiscovery.exe` value in the `Process Name` column, and click `Include 'EDDiscovery.exe'`
* Scroll to the bottom, and see if there's an event for `EDDUser.sqlite` or `EDDSystem.sqlite`
