### ISSUE TITLE
Idea - Estimated value since last docking

### ISSUE THREAD

**Issue by dthomson39** [EDDiscovery/EDDiscovery#1209]
I thought it might be useful to get some idea of estimated value of the various places explored - I have extracted the data and filtered it in excel but to do that from the click of an option or a specific search would be useful I think.
It might also be extended to give feedback on how efficiently you are gathering valued data (presumably on value) so you could look at efficiency over a specific period - maybe your trying a new approach etc
- just a thought.

**Comment by iainross** [comment]
Have a look at the Travel tab on the Statistics table - in Summary mode it will give you the number of jumps and scans, estimated total value and ly travelled since you last docked (as well as the last 24h, week, month and forever).  You can define custom periods as well if you want to slice it differently.

**Comment by dthomson39** [comment]
Many thanks - didn't notice the link so missed the obvious - very useful tools and app
