### ISSUE TITLE
Data from beta journal sent to live servers

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#1226]
I am currently testing 2.4 open beta 1, specifically the new functionality of the nav beacons.  While ED Disocvery correctly detects that I am in beta, it sends the journal messages to the normal EDDN endpoints.  As a result, data from beta scans in showing up in live EDDB, among others.

Example: https://ross.eddb.io/body/update/54 , updated by this EDDN message: https://ross.eddb.io/eddn/log/42397317

**Comment by CMDR-Cometborne** [comment]
Further testing showed that this only happens if the users creates an EDSM account with a name that is not [BETA] $commandername. Once I deleted the extra EDSM account information, the uploader ID switches from betaborne to "[BETA] Cometborne", and the messages start using the test schema

**Comment by Athanasius** [comment]
Looking around the code I *think* the issue is with:

https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/EDDN/EDDNClass.cs#L61

I can't be 100% sure, due to being new to the codebase, but if that's the same commandername that you're allowed to edit then the test is bogus.  Is that 'Beta' from EliteDangerous/JournalEvents/JournalFileheader.cs exposed to be used in this instead ?

**Comment by andybish** [comment]
i think it's the above, plus this: https://github.com/EDDiscovery/EDDiscovery/blob/a1bbc4761bae7daf6df3955b50260ba6d88d3492/EliteDangerous/EDDN/EDDNSync.cs#L137
when the beta cmdr has an edsm name, that's used in place of the cmdr name that starts with [BETA]

**Comment by robbyxp1** [comment]
Fixed
