### ISSUE TITLE
Add warning about exploration data piracy on EDSM

### ISSUE THREAD

**Issue by ToBeFree** [EDDiscovery/EDDiscovery#1265]
Players who want their name on rare findings should not use EDDiscovery *during* a trip.

https://www.reddit.com/r/EliteDangerous/comments/6zfy3z/edsm_exploration_data_piracy_be_careful/

**Comment by klightspeed** [comment]
One can disable `Sync to EDDN` during the trip to prevent scans from being sent, and use the `Send unsynced scans` menu option to send the scans once the scans have been sold.

**Comment by ToBeFree** [comment]
Yeah, that's nice :) I just thought the software could suggest to do this during trips on the first start.

**Comment by robbyxp1** [comment]
Hard to know when your going somewhere..  No action sorry.

**Comment by EoD** [comment]
It might be a good idea to add some mode for "Don't send any scans to EDDN if the scan is not already on the EDSM download" - "Secret Scan Mode?"

So all other events (like faction, station, etc) are still be sent to EDDN.

**Comment by klightspeed** [comment]
That would require always downloading the EDSM bodies, regardless of whether the EDSM button on a scan panel is checked, and regardless of whether a voice pack is annunciating the bodies list.

**Comment by phroggster** [comment]
The suggested "Hide Scans Mode" or "Privacy Mode" could be accomplished in theory, but I have a hard time envisioning a functional UI that would work with it. Also, if there's stations in the system, the scans from others are probably already loaded in EDDB/EDSM; you're certainly not discovering a new massive Earth-like that you're going to need to keep under wraps in order to collect the discovery bonus before the pirates do.

I do see the value in adding something like this, but the only workable solution that I could really come up with to solve it would be a global "Offline Mode." With the exception of anonymous EDD application update checks and anonymous GalMap downloads, the entire program would run without sending or receiving any other data. That's technically workable, avoids the "problem" of first discovery piracy, and also avoids the inevitable "I had privacy mode enabled but EDD still sent a jump event for (some event in a populated system) and someone destroyed my ship because of it" issues.
