### ISSUE TITLE
Enable to log onto FD API.

### ISSUE THREAD

**Issue by Gentleman-Thug** [EDDiscovery/EDDiscovery#1359]
Consistent message:

"Companion API is temporarily disabled due to changes in the API by Frontier for 2.4. As Arnie says Ill be back"

I am reading other users have API access. When will this be resolved. I have uninstalled and reinstalled, have validated game files and have cleared my FD API and resubmitted new ones 5 times. no joy.

Any advice?

**Comment by phroggster** [comment]
It's intentionally disabled on our end. Since FDev only reactivated the API fairly recently, we have not had enough time to verify that we're not doing anything catastrophic with it, like deleting our user's ED licenses or something. After we've verified our interactions with it, a new version of EDD will be released that will re-enable the companion API. When you see the New Release notification at the top of EDD, or something added to our [Releases page](https://github.com/EDDiscovery/EDDiscovery/releases), expect it to be working once you've updated.

**Comment by Gentleman-Thug** [comment]
Lee, 

Thanks for that very swift reply mate. 

Love the product, very very professional, would not use anything else.

Regards,

Darren Jackson
