### ISSUE TITLE
Crash when deleting journal entries (8.4 pre-release)

### ISSUE THREAD

**Issue by MartindForlon** [EDDiscovery/EDDiscovery#1426]
Hi, there is irregularly happening crash when you are deleting journal entries. Details are posted below.

There was an unhandled UI exception.

```
==== BEGIN ====
System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked
   v System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   v System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   v System.Data.SQLite.SQLiteDataReader.NextResult()
   v System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   v System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   v EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock)
   v EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)
   v EliteDangerousCore.DB.SystemClassDB.GetEdsmIdsFromName(String name, SQLiteConnectionSystem cn, Boolean uselike)
   v EliteDangerousCore.DB.SystemClassDB.GetSystemsByName(String name, SQLiteConnectionSystem cn, Boolean uselike, Boolean useedsm)
   v EliteDangerousCore.DB.SystemClassDB.FindEDSM(ISystem s, SQLiteConnectionSystem conn, Boolean useedsm)
   v EliteDangerousCore.SystemCache.FindEDSM(ISystem sys, Boolean usedb, Boolean useedsm, SQLiteConnectionSystem conn)
   v EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos, ISystem edsmsys, Boolean reload, SQLiteConnectionUser uconn, Boolean useedsm)
   v EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl)
   v EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
   v EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()
   v System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   v System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   v System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====
```

**Comment by klightspeed** [comment]
That looks like a slow system DB - SQLite throws that exception when the database is locked by another command (e.g. a running insert) for more than a few seconds.

Please attach the related trace log.

**Comment by MartindForlon** [comment]
Sorry, new in this. From where I can get mentioned trace-log?

**Comment by klightspeed** [comment]
Trace logs are by default located in `%LOCALAPPDATA%\EDDiscovery\Log` for the installed version, and `Data\Log` for the portable version.

**Comment by MartindForlon** [comment]
[Trace_logs.zip](https://github.com/EDDiscovery/EDDiscovery/files/1430203/Trace_logs.zip)

Here is few latest, all had crash on the end.

**Comment by klightspeed** [comment]
Trace_20171030135101.0.log: https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/UserControlScreenshot.cs#L75 - looks like the screenshotconverter may not be set yet in EDDiscoveryForm, and you chose to abort rather than ignore.

Trace_20171030135816.0.log: same as above, though with a slow EDSystems.sqlite database.

Trace_20171030135952.0.log: Looks like the EDDSystems.sqlite database was slow, the EDSM dump download broke, and then a minute later the UI ran into problems with the slow database.

Trace_20171030140643.0.log: This time, the EDDUser.sqlite is starting to become a little bit slow, and you ran into the same issue as with the first trace log.

Trace_20171030141747.0.log: Once again, slow EDDSystems.sqlite database.

You might need to delete `%LOCALAPPDATA%\EDDiscovery\EDDSystem.sqlite` in order to try to fix the "database is locked" issues (and if possible don't choose Abort if a UI exception occurs while the EDSM systems are still being synced), and we'll need to look into the issue causing the screenshot panel to sometimes error out.

We also need to figure out some way to reduce the reliance on the full EDSM dump (while also keeping the number of EDSM requests low), and/or figure out a way of having a downloadable compressed dump without affecting performance or memory usage too much.

The end-of-file on the stream on the download is suspicious - if the HTTPS connection broke, I would have expected a "Connection reset by peer", not an "Unexpected end of file".

**Comment by MartindForlon** [comment]
Is here something more I can do to help? (will try delete that sqlite file and see result)

**Comment by klightspeed** [comment]
If you can download https://www.edsm.net/dump/systemsWithCoordinates.json and see how big it is, that might help.  It is just over 2GB at the moment.

If that succeeds, then you should be able to rename it to `edsmsystems.json`, put it into `%LOCALAPPDATA%\EDDiscovery`, and create an empty `edsmsystems.json.etag` file.

One way to create such a file is:
* Open Notepad
* File -> Save
* Browse to `%LOCALAPPDATA%\EDDiscovery`
* Save as type: All Files
* File name: `edsmsystems.json.etag`
* Encoding: ANSI
* Save

**Comment by MartindForlon** [comment]
ok, I did all this requested. Downloaded file size is 2.1 GB

**Comment by robbyxp1** [comment]
No further progress, closing
