### ISSUE TITLE
EDDiscovery Error when use freevoice add-on just after installation.

### ISSUE THREAD

**Issue by wrinos** [EDDiscovery/EDDiscovery#1574]
### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: 필수 ID의 인식기가 없습니다.
>매개 변수 이름: culture
>   위치: System.Speech.Recognition.SpeechRecognitionEngine..ctor(CultureInfo culture)
>   위치: AudioExtensions.VoiceRecognitionWindows.Open(CultureInfo ctp) 파일 C:\Code\EDDiscovery\Audio\VoiceRecognitionWindows.cs:줄 37
>   위치: EDDiscovery.Actions.ActionPerform.ExecuteAction(ActionProgramRun ap) 파일 C:\Code\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionPerform.cs:줄 116
>   위치: ActionLanguage.ActionRun.DoExecute() 파일 C:\Code\EDDiscovery\ActionLanguage\ActionsCore\ActionRun.cs:줄 184
>   위치: EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, ConditionVariables additionalvars, String flagstart, Boolean now) 파일 C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:줄 524
>   위치: EDDiscovery.Actions.ActionController.ManagerAddOns(Boolean manage) 파일 C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:줄 390
>   위치: EDDiscovery.EDDiscoveryForm.manageAddOnsToolStripMenuItem_Click(Object sender, EventArgs e) 파일 C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:줄 1428
>   위치: System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   위치: System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   위치: System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   위치: System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   위치: System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   위치: System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   위치: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   위치: System.Windows.Forms.Control.WndProc(Message& m)
>   위치: System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   위치: System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
You currently need the en-GB windows language pack installed.

On 26 Dec 2017 9:00 PM, "wrinos" <notifications@github.com> wrote:

Description Additional Information Exception Details:

There was an unhandled UI exception.

==== BEGIN ====
System.ArgumentException: 필수 ID의 인식기가 없습니다.
매개 변수 이름: culture
  위치: System.Speech.Recognition.SpeechRecognitionEngine..ctor(CultureInfo
culture)
  위치: AudioExtensions.VoiceRecognitionWindows.Open(CultureInfo ctp) 파일
C:\Code\EDDiscovery\Audio\VoiceRecognitionWindows.cs:줄 37
  위치: EDDiscovery.Actions.ActionPerform.ExecuteAction(ActionProgramRun
ap) 파일 C:\Code\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionPerform.cs:줄
116
  위치: ActionLanguage.ActionRun.DoExecute() 파일
C:\Code\EDDiscovery\ActionLanguage\ActionsCore\ActionRun.cs:줄 184
  위치: EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev,
HistoryEntry he, ConditionVariables additionalvars, String flagstart,
Boolean now) 파일
C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:줄 524
  위치: EDDiscovery.Actions.ActionController.ManagerAddOns(Boolean
manage) 파일 C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:줄
390
  위치: EDDiscovery.EDDiscoveryForm.manageAddOnsToolStripMenuItem_Click(Object
sender, EventArgs e) 파일
C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:줄 1428
  위치: System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
  위치: System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
  위치: System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
  위치: System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
  위치: System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
  위치: System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
  위치: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
  위치: System.Windows.Forms.Control.WndProc(Message& m)
  위치: System.Windows.Forms.ToolStrip.WndProc(Message& m)
  위치: System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
  위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32
msg, IntPtr wparam, IntPtr lparam)
===== END =====

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EDDiscovery/EDDiscovery/issues/1574>, or mute the thread

**Comment by robbyxp1** [comment]
I need to make it clearer!

**Comment by wrinos** [comment]
This is a problem that occurs because the operating system's speech recognition feature is not installed or supported.
Thank you reply.
