### ISSUE TITLE
Regression: Update dialog no longer shows button to download portable version

### ISSUE THREAD

**Issue by radioactiv** [EDDiscovery/EDDiscovery#1611]
The update dialog used to have a button to directly download the portable version, in the same way it now has a button for the installed version.

**Comment by phroggster** [comment]
Some screenshots of this in action, since no one will see it for another two releases (one to get the fix, and another to see the update notification):
![windefault](https://user-images.githubusercontent.com/14035789/34846105-ba66cc64-f6dc-11e7-9628-f1aed65bb9fb.png)
![orange_delight](https://user-images.githubusercontent.com/14035789/34846140-d75dcffc-f6dc-11e7-8916-7273598873d3.png)

**Comment by phroggster** [comment]
Sorry, that comment was meant for the pull request (#1614), but I guess you can see them, too. 😉

**Comment by phroggster** [comment]
Should be fixed in 9.0.3, out within (roughly) the next week.
