### ISSUE TITLE
New EDSM theme requires Arial Narrow font

### ISSUE THREAD

**Issue by Taomyn** [EDDiscovery/EDDiscovery#1639]
New EDSM theme requires Arial Narrow font which doesn't come with Windows 10. Luckily my other machine has Office 2016 so could grab it from there. Officially this font has to be bought or obtained under licence.

**Comment by phroggster** [comment]
Yes, that is accurate. You can try installing an old [hotfix from Microsoft](https://support.microsoft.com/en-gb/help/956514/description-of-the-2007-office-hotfix-package-gfonts-msp-august-26--20) (intended for Office 2007, but that is not listed as a prerequisite) that includes the Arial Narrow faces, or searching Google for a number of free-for-personal-use-but-not-for-us-to-include-in-the-installer download links. Otherwise, we'd have to put together a sizable chunk of money (> $200 USD) to purchase an app font license for it, something that we're unlikely to be able to do.

**Comment by Taomyn** [comment]
No worries, was reporting to be sure this was an accidental oversight i.e. was developed/rested on machines that just happened to have the font already present.

I have to say I quite like it - a very smart looking theme

**Comment by robbyxp1** [comment]
Ack will fix

**Comment by robbyxp1** [comment]
Fixed on 9.04 and master
