### ISSUE TITLE
Multiple Commanders - Really doesn't work

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#164]
Has anyone tested this functionality?  I finally purchased my second commander and wanted to track his progress from the beginning... I set up a second commander in EDD, and even got a EDSM API key and all. It actually seemed to work OK, with me being able to flick between the two commanders, and them having two different travel histories.  But after logging off Elite and EDD one night and coming back to it a few days later, the two commanders travels are merged into one travel history (the original commander's) and the second commander having nothing.

Will this have screwed my original travel data?  Can I send any files in for someone to analyze?  I can certainly show screenshots.

**Comment by klightspeed** [comment]
The commander ID is never set before adding the visited systems to the database.

**Comment by Red13x3** [comment]
![2016-04-04_214926](https://cloud.githubusercontent.com/assets/13119623/14247222/044e8e3c-fab0-11e5-8f74-35114ccf881d.png)

**Comment by Red13x3** [comment]
As you can see from the above, the records 91 and onwards are from my Red_13 character that is in the Black doing exploring... And my Red_XIII character is in the human bubble doing missions, shown from record 90 and lower.  If I select the Red_XIII commander, nothing shows up in the history. The original commander (Red_13) has all the data. :(

**Comment by finwen** [comment]
Multi commander is limited and need allot of improvements. But you can move
data to another commander.

My shoulder interfered with my work on it allot but  now i  am slowly back
on working on EDD again. I have 2 commanders and will work on some
improvements soon :)

2016-04-04 14:00 GMT+02:00 Mark <notifications@github.com>:

**Comment by Red13x3** [comment]
Hi Finwen... You mentioned being able to move data to another commander... Can you tell us how to do that?  Also, if I'm moving from one computer to another, can I safely grab the data file and move it to the new computer?

**Comment by Red13x3** [comment]
When going to Add the second commander, the first commander is listed as being number "0" and when you add the new one, it is defaulted as number "2"... Yet when you restart the app, the commander 0 is actually duplicated to "1" as well, so you have three commanders listed.

Also, another problem: It does not remember which commander you had selected last before quitting and each time you start the app, it defaults back to the first commander you had created.

**Comment by klightspeed** [comment]
> You mentioned being able to move data to another commander... Can you tell us how to do that?

Select the entries to be moved from the travel history list, right-click them, and click the "Move to another commander" option.

> Also, if I'm moving from one computer to another, can I safely grab the data file and move it to the new computer?

Everything is stored in `%LOCALAPPDATA%\EDDiscovery`, so one should be able to copy everything from that directory on the old computer to the equivalent directory on the new computer (creating the `%LOCALAPPDATA%\EDDiscovery` directory if needed).

> When going to Add the second commander, the first commander is listed as being number "0" and when you add the new one, it is defaulted as number "2"... Yet when you restart the app, the commander 0 is actually duplicated to "1" as well, so you have three commanders listed.

I suspect that the issue here is that `EDDiscoveryForm.EDDConfig` indexes the commanders sequentially, while everything else refers to the commanders by the ID in the database.

Additionally, due to the `EDDiscoveryForm.EDDConfig.CurrentCmdrID` not being set when the active commander is set, any submissions probably also go to the EDSM account of the first commander.  I intend to create a pull request to fix this, and to have `EDDiscoveryForm.EDDConfig.CurrentCmdrID` represent the Database commander ID rather than the sequential index in the commanders list.  The `listCommanders` field can probably also be encapsulated by e.g. a `Commanders` property indexed by commander ID.

> Also, another problem: It does not remember which commander you had selected last before quitting and each time you start the app, it defaults back to the first commander you had created.

Perhaps the last active commander can be stored in e.g. an `ActiveCommander` setting in the database.

An additional issue I found is that the per-commander netlog paths are not hooked up to the netlog watcher, and are not stored in the database.  The netlog path is also not updated in the netlog watcher until the application is restarted.  I am looking at implementing some way of allowing the watcher to watch multiple directories, and assign the logs from those directories to the appropriate commander(s).

**Comment by finwen** [comment]
I have made improvments and bugfixes to  multicommander that will be in
3.1.0.

2016-04-27 9:35 GMT+02:00 Ben Peddell <notifications@github.com>:

**Comment by Red13x3** [comment]
Thanks for the excellent replies, Ben!

Look forward to seeing any fixes for this, as I'd love to safely run both commanders off the one (main gaming) computer. At present, I don't want to mess the data up from my primary exploring commander and so I'm running my second commander in a second (non-gaming) machine, only. 

Thanks again for picking this thread up. :)

CMDR Red_13

--
Mark
iPhone: 0402 322 901

**Comment by klightspeed** [comment]
Most of the issues with multiple commanders should be resolved in 3.1.0

Please let us know if you still have the duplicate commander in the dropdown list.

**Comment by mwerle** [comment]
Selecting the "Hidden Log" no longer shows hidden log entries - log view is unchanged from previously selected Commander.  This means it's currently impossible to unhide log entries.
Trunk: 09f176589d677e544a726bb030f76e1eaad073ee
Already broken in: 4c3e9492ced793d9ee9748a699bdb161a3e6b5e0

**Comment by klightspeed** [comment]
@mwerle #207 should fix this.

**Comment by mwerle** [comment]
It does appear to, thanks.
