### ISSUE TITLE
custom %localappdata%\EDDiscovery location

### ISSUE THREAD

**Issue by draeath** [EDDiscovery/EDDiscovery#1666]
I've recently added an SSD to my system, and I use NTFS symbolic links to move items to this SSD without having to reinstall applications.

Unfortunately, EDDiscovery seems to wipe out the link when it is installed in an update.

It would be wonderful, as an alternative, if we could select where the data (sqlite databases, etc) are resident, instead of "forcing" them to exist in the user profile.

**Comment by iainross** [comment]
Hold down the shift key while you launch edd for a number of options including one to move the databases

**Comment by draeath** [comment]
That's useful, but i might suggest a command line argument to invoke that as well.

**Comment by phroggster** [comment]
Use "-appfolder X:\EDDisco\Path\Data", or use the portable zip distribution which will store data alongside EDDiscovery.exe in a Data subfolder.

The junctions getting wiped during updates is due to the fact that the installer technically owns the localappdata folder that we utilize. It's not happy when it notices that it's not a regular directory, so it wipes the junction and starts fresh. There's little that we can do about that, except switch to a different installer platform or add 3+ options to store the data elsewhere
