### ISSUE TITLE
Make travelgrid columns configurable - such as exploration columns

### ISSUE THREAD

**Issue by rysulliv** [EDDiscovery/EDDiscovery#1808]
Why don't you allow the estimated payout total to be a column on the exploration panel? You have the info and it would be great to have an idea and running total of your trip's value. You could add it to the route tracker too so you have a running total. Would be aweomse.

**Comment by robbyxp1** [comment]
We won't be adding any more columns to the travelgrid directly, but we may make it more configurable..

being able to add/remove columns might be a good idea.

**Comment by rysulliv** [comment]
Yea configurable would be great. And agreed, it would be after you scan, but it would be nice to know how much you have earned so you can decide when to turn back etc.

Also the near by stars would be awesome to have star type/scoopable in case you screw up. Just like using the tool more than the galaxy map

**Comment by robbyxp1** [comment]
Can't get info on other stars without an expensive web lookup.

Right click on header to configure columns as well..

**Comment by iainross** [comment]
The Statistics Panel can give you the estimated value of all your scans since you last docked, and I'm just in the middle of testing having a column in the summary view there to show you totals since the last Start Marker in your travel history (if there's no matching end marker yet) so that will allow you to easily customise that for subsections of a trip by the next release.

**Comment by robbyxp1** [comment]
Closing this, as adding it to the exploration panel is very difficult as its not linked to history, and it requires long EDSM lookups.
