### ISSUE TITLE
Allow use of an external MySQL/MariaDB or PostgreSQL database

### ISSUE THREAD

**Issue by davidmarshall15** [EDDiscovery/EDDiscovery#1984]
Has the use of an external MySQL/MariaDB database been considered? 
I appreciate there would only be a small number of people who would benefit, don't expect many to have dedicated db servers running on their LAN but it would be a nice feature.

A PostgreSQL option would be even better, considering it's reliability and easy to hot backup and restore, but as this would be a much bigger change, it is probably not worth the effort.

Offloading the database to an external server and having control over backups would be great.
I know EDToolBox allows this (MySQL/MariaDB only) so I wondered if has been discussed/thought about here.

Thanks for reading

**Comment by klightspeed** [comment]
The current schema evolved with SQLite being the sole database provider, and as such is quite loose.

We would need to tighten the schema definition to make it more compatible with other databases (e.g. using `VARCHAR` instead of `TEXT` as has been used).

For compactness, we would also need to define the integer column sizes (e.g. `TINYINT`) instead of just using `INTEGER` and `FLOAT`, and use `BIT` instead of `BOOL`.

The schema also depends on SQLite's `IF NOT EXISTS` and `IF EXISTS` for DDL updates.

DDL updates differ between databases, so I think the best course of action would be to hand off database creation to the user if they specify a database connection in the app.config, and provide generic schemas that are reasonably compatible between databases (e.g. using data types such as FLOAT(24), FLOAT(52), INT, NVARCHAR).

The current Systems table population would also need to change, as it currently inserts the systems from the json in bulk into a new table, then deletes the old table, renames the new table, and creates the indexes.  It was tuned for SQLite, which does not support `INSERT BULK` or `LOAD DATA`.

The database locking in EDDiscovery is also coded around SQLite only supporting database-level locks, and as such is fairly pessimistic.

While providing support for specifying a different database is fairly simple (see https://github.com/EDDiscovery/EDDiscovery/compare/master...klightspeed:master-dbprovider-overload - we already use a DbProviderFactory for switching between System.Data.SQLite and Mono.Data.Sqlite), anything involving DDL would need to depend on what the database provider supports.

**Comment by robbyxp1** [comment]
I think the amount of re-work/risk vs the number of people it would payoff for means its probably not worth it.  

Also, if the DB is remote, its going to affect performance especially with the system db...

**Comment by davidmarshall15** [comment]
If it's probably considered not worth it, then fair enough.
I do have multiple SSD's and can at least put the 6GB+ system db on a less used drive.

Anyone who can standup a postgres or mariadb/mysql, would probably realise that it has to be on their LAN, I wouldn't expect anyone to be using a database externally on the WAN for this.
A separate server on the LAN makes sense to me, send a SQL statement, the DB server does the grunt and returns a small set of rows.

If this is further considered, I am happy to look at the schema definitions for postgres and mariadb/mysql, I have been an oracle DBA for near 30 years so working on schema definitions is something I can do.

Hand off database creation to the user is how EDToolbox approaches this, the user can either use the bundled mysql database or update the connect string to point at an external database, if I remember correctly it was limited to mariadb/mysql

**Comment by robbyxp1** [comment]
Well, with thousands of users now, a re-write like this, for just a few users, is not worth the risk involved.  The DB code is stable (after a lot of trouble) and I personally would not risk changing it unless there is overwhelming demand.

Sorry!
