### ISSUE TITLE
[ER] Add SHIP TARGETED event into COMBAT tab

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#2141]
I was thinking... would it be feasible to put the "SHIP TARGETED" entry into the combat tab?  

I ask this question because the "rank" on the "INTERDICTED" event is always wrong (rank doesn't show up in that event data) and should probably be removed (the only way to determine it from the JSON is if the ship was targeted before the interdiction).

Which got me to thinking, if "SHIP TARGETED" was in the combat tab, I could follow that chain of events without switching tabs to see what rank he was.  This would probably be simpler than hoping someone had the smarts to press "h" while interdicted. It also allows for the scenario where you know you are going to be interdicted, but you drop out of supercruise before that happens. 

It's kind of sad that there is no proper reference in the JSON from ED (not EDD) that gets the rank mentioned at all except for the SHIP TARGETED event.. some correlation would be nice from the Frontier Devs :-P

Thanks for listening.

**Comment by klightspeed** [comment]
`CombatRank` only shows up in the `Interdicted` and `Interdiction` events if the interdictor (if being interdicted) or victim (if you are doing the interdiction) is a player.

The issue is that `CombatRank` is non-nullable in the EDDiscovery `Interdicted` and `Interdiction` events, so if not present it will always default to `Harmless`.

**Comment by robbyxp1** [comment]
After that fix, add the target info into the combat panel

**Comment by robbyxp1** [comment]
10.4 will be done

**Comment by robbyxp1** [comment]
10.4 implemented.
