### ISSUE TITLE
Exporting to EDShipyard doesn't export the ship data

### ISSUE THREAD

**Issue by eplossl** [EDDiscovery/EDDiscovery#2283]
When exporting to EDShipyard, the data goes to the old version of the EDShipyard (edshipyard.com) which is currently no longer being maintained, instead of going to the new version (edshipyard.net) which is current.  Is there a way this can be changed in the config files, or is this something that has to be changed on the backend?

**Comment by robbyxp1** [comment]
This is a known issue which we have been struggling with.

We don't support edshiptyard.net due to licensing problems with that site.  The code was copied from the original owners site without explicit permission from him.  It has a copyright of

"Except where noted otherwise, all design, markup and script code for edshipyard.com is copyright (c) 2015,2016 taleden
and is provided under a Creative Commons Attribution-NonCommercial 4.0 International License (http://creativecommons.org/licenses/by-nc/4.0/)."

Taleden to EDCD knowledge has not released copyright on it..


Saying that, i'll think about allowing users to personally configure the site for coriolis and edshipyard so its up to you to decide where you send your data.  Then I don't have that ethical dilemna!

**Comment by robbyxp1** [comment]
10.4 - right click on the icons and you can configure the URLs...
