### ISSUE TITLE
[Suggestion] Travel History Tab & Exploration Tab integration

### ISSUE THREAD

**Issue by Lethann** [EDDiscovery/EDDiscovery#2292]
If there is already a way to do this please tell me how, otherwise here is my suggestion:

Being relatively new to the game I was wanting a way to list all the systems I've been in and if they have been scanned or not. I can easily see the information on the "exploration" tab, however I currently only know of manually entering in all the systems while reading my Travel History tab since I don't know of a site to download a json file of my visited systems. Would it be possible to either have a button on the exploration tab for "grab all visited" or at the very least adding a right click menu option of "add system to exploration" on the Travel History tab?  It already has the trilateration tab option. 

edit: And yes I see the other suggestion about the overlay but honestly that's not what I'm looking for. I would like a list of what systems I should go back and scan and bonus if the scan was complete or not.

**Comment by iainross** [comment]
The exploration tab has a scan count, but it won't tell you whether the scan was complete from a bonus perspective.  For systems since 3.3 dropped there is an FSS All Bodies Found journal so I guess you're looking for a list of systems visited with a flag to say whether that journal exists for the system?

Prior to 3.3 we can't tell if you've completely scanned the system because we don't know if a body exists until it's been scanned...

**Comment by Lethann** [comment]
Yea, I didn't think that the 'complete system scan' would be even possible to add. Honestly the info that the exploration tab has on it is exactly what i'm looking for: name, distance, visits, scans, star type and notes. Can always go in the 'notes' section and say when a system is complete. That's really why i'm only asking for a way to shove that data into the exploration tab and not asking for a completely new tab.

**Comment by robbyxp1** [comment]
For 10.4. Thanks for the suggestion.
