### ISSUE TITLE
"First Discoveries" Statistic Does not update

### ISSUE THREAD

**Issue by AndrielChaoti** [EDDiscovery/EDDiscovery#2392]
The "First Discoveries" entry in the Statistic panel does not ever increment or update.
![image](https://user-images.githubusercontent.com/3628387/51763311-81b44d00-208f-11e9-97ee-d221d967e6ca.png)
I know for a fact that this number is not 0, for both contexts of EDSM first discoveries and actual ingame first discoveries. (In my case it should be 861 if it is counting EDSM first discoveries.)

**Comment by iainross** [comment]
It is not counting EDSM first discoveries, only in game ones so it only updates when the data is sold.

Alas in 3.3 FD introduced a new multisell exploration data journal which is used when you sell a whole page and this does not tell you how many bodies you tagged or which ones - although for now the sale of data one system at a time does still give us that.

So it is a count of tags gained for sales between the introduction of journals (in 2.something) and 3.3 plus any gained from individual system sales since 3.3 dropped.

Additionally all stats are calculated on the fly from loaded history currently and so will only be accurate if you have Only Read Essential Entries disabled on the settings tab or Essential Entries Are set to All entries for Statistics.

**Comment by AndrielChaoti** [comment]
Okay. I've only been using multi-sell, so that makes sense.
