### ISSUE TITLE
Fatal error v. 11.0.3

### ISSUE THREAD

**Issue by CommanderDiffin** [EDDiscovery/EDDiscovery#2584]
Don't publish stuff that doesn't work. I like stuff that you install and it just works.

What I _don't_ like, is stuff that shouts at me PLEASE BE PATIENT and then threatens to update my 'system database' (whatever that is) to make it smaller. Then tells me it will take a while (how long is 'a while'?) dependent on where the 'star database' (what is that the same thing as the 'system database'?) is (how should I know?) And then warns me to beware that if I try to use the program whilst it is updating it will crash, but just rerun the program. And so then I have to check on the forums to see how much disk space this database takes up. And then there is no clear answer. Someone says maybe 7GB. That is too much. Someone else says it took them 23 hours to download. Someone else says 12 hours or something. And then all else I see is people with catastrophic problems with the software ruining their flight history. And then I run the program anyway and I can't tell if it's updating anything because it doesn't say, and I leave it on all day. And then I check it hours later and find that it's crashed anyway without me doing anything with it, and left me with a fatal error window. And then I rerun the program from my desktop icon as per the instructions and the previous working version runs instead. And then when I look in the Program Files folder I can't find the faulty new version. And then when I click Report on the fatal error window it makes me sign up to Github that I never wanted to join. And then Github tells me my username is no good. And then that my password is not safe enough, as if Github has anything important on it, as if I care. And now. So I have been patient.

I don't like any of that stuff. So I don't like 11.0.3. And I don't like that you've wasted my time with it. You need to withdraw 11.0.3 and tell everyone to keep using 10.6. I like 10.6. You install it, and it just works.

**Comment by klightspeed** [comment]
The current full systems DB (i.e. `%LOCALAPPDATA%\EDDiscovery\EDDSystem.sqlite` - the database that holds all of the systems downloaded from EDSM) in 10.6 is about 7+GB.

The current full systems DB in 11.x is about 3GB.

If you don't want the systems DB to be populated using data downloaded from EDSM, then uncheck `Download EDSM star data` in the Settings panel.

Note that the error that caused `UnKnown` FSDJumps to be added to the history occurred when players had `Sync From EDSM` set in their commander settings, and was fixed in 11.0.2.

The status of the Systems DB import should be displayed in the status bar at the bottom of the program window.

In order to assist in fixing whatever caused your crashes, would it please be possible to get the error details from the most recent trace logs `Trace_*.log` from `%LOCALAPPDATA%\EDDiscovery\Log`?  We don't have Telemetry, so we don't know what errors users have unless those users submit those errors.

**Comment by robbyxp1** [comment]
Going to close this, as we are not going to withdraw 11.0.3.  There was a very good reason why we changed the db.
