### ISSUE TITLE
[Question/Organizing] Are commits/PRs for linux compatibility welcome?

### ISSUE THREAD

**Issue by CommanderStrax** [EDDiscovery/EDDiscovery#2587]
Hi,

I stumbled over this project today (patch day, yay) and got quite intrigued when I noticed you guys weren't using WPF but WindowsForms. I downloaded everything and, after disabling the Audio part via the appropiate switches and switching some AutoSize properties to false, got the program running. Even the 3D map is working :+1: 

Question is: Is this project interested in getting this to work on Linux more or less properly (there are still some glitches that have to do with mouse down events 'n stuff), as long as Windows usability isn't impacted?

I would like to get that out of the way before I start firing PRs ;)

**Comment by klightspeed** [comment]
Building it with `NO_SYSTEM_SPEECH` should disable the audio system when building (since there is no System.Speech` in mono).

There is also a net core 3.0 branch (`master-netstandard`), though that is mostly untested.

Please feel free to submit pull requests to improve mono compatibility.  We have a Travis CI build just to make sure we don't break the ability to build under Linux.

**Comment by robbyxp1** [comment]
I welcome pushes.  

The bigger they are, the slower they will be to be accepted in.  Minor tweaks to a few files is easy to accept, big re-org (like the one with the system db) take a long time to hit a release.

13400 people downloaded 10.6, so i'm wary of pushing out experimental stuff without long verification periods now.

thanks
