### ISSUE TITLE
Feature request: Allow the EDSM database to be moved

### ISSUE THREAD

**Issue by cristi-neagu** [EDDiscovery/EDDiscovery#2711]
Hello,

The EDSM database takes up a lot of space on the C drive. So, as the title suggests, can we please have the option to move it to a different location, just like we can with the other databases?

Hint, hint, nudge, nudge: https://github.com/EDDiscovery/EDDiscovery/blob/6dd9982e259e23b4650df0ffb0c65cc2e8e18058/EDDiscovery/EDDiscoveryControllerSync.cs#L128

Thank you.

**Comment by robbyxp1** [comment]
This file is temporary and is deleted after being read (line 145). It can either go there, or into your temp folder.  The reason we chose there is because its matched with the drive you store the database on.

You can also choose which drive to place the appdata on, or chose to have appdata on one drive and the systems db on another.

I think that covers all the possibilities and I can't that we need to support more.

rob

**Comment by cristi-neagu** [comment]
Ah, I didn't know it's a temporary file. That should be ok, then.

Thank you.
