### ISSUE TITLE
Feature-request | Expedition-Panel | Download waypoints

### ISSUE THREAD

**Issue by Envisitor** [EDDiscovery/EDDiscovery#2772]
Hello,
Would it be possible that EDD downloads the waypoints from the expedition-panel without the need that it downloads a whole region/sector? 
Downloading a whole sector/region instead of just downloading needed systems fills the database with probably unnecessary entries. This costs also ressources.
Kind regards
Envisitor

**Comment by robbyxp1** [comment]
Not clear to me. "Downloads the waypoints".  What do you mean by download? Do you mean from EDSM?

**Comment by robbyxp1** [comment]
If you mean an EDSM download to the star database of only the stars in the expedition panel, then that's not possible.  The database works on grid sectors, and can't handle anything less than than a sector on that grid.

**Comment by klightspeed** [comment]
I'm guessing meaning doing a `api-v1/systems` query, possibly with all of the waypoints in the `systemName[]` parameters?

**Comment by Envisitor** [comment]
Sorry for the late answer and that I expressed myself so incomprehensible. 
I mean what klightspeed said.

> I'm guessing meaning doing a `api-v1/systems` query, possibly with all of the waypoints in the `systemName[]` parameters?

**Comment by robbyxp1** [comment]
I'll keep it in mind, but don't expect it to happen soon, or if every, due to this:

The only place we store stars in in the system db, and that has its own download mechanism as you know which tracks which stars have been downloaded to the db.   Downloading discrete sets of stars into it would need careful consideration and lots of testing.

The EDSM website also limits queries per hour which may affect how we could pick up a set of stars.

The other download mechanisms from EDSM present stars in the list but they do not store the data into the DB.  We could obv do the same here but then the data would be lost on the next load and also the data would not be presented in the other panels.

All in all, its a decent amount of redesign.  I'll add it to my list of things to investigate. 

In the meanwhile, closing this and I don't leave pending enhancements in this list.

Thanks for the idea.
