### ISSUE TITLE
Estimated value not updating after full scan

### ISSUE THREAD

**Issue by rastitkac** [EDDiscovery/EDDiscovery#2857]
Hi there,

I have updated from version 10.* to current release 11.5.3.
I was used to that est value field in estimated value window would update value after i scanned a body.
Now it doesn't and instead stays on the initial value.

Is this new behavior normal, or is something wrong.

Best Regards,
Rasti

**Comment by robbyxp1** [comment]
From the look of things, it will update on a new entry or a move position on the history panel.

I'll have to check it out.

**Comment by rastitkac** [comment]
Yes, that is what it used to do; update the value and move the scanned entry to the top.
If there is anything I can do to help you investigate, let me know, I will be back online at 20:00 CEST.

**Comment by robbyxp1** [comment]
So, this was changed so we compute the estimated values of the body without scan, with discovered, with mapped etc.

You can see all the values in the report that is given on a body in the scan panel.

The estimated value show the best estimate of the maximum value you can get - based on the info we have.  So it won't change if its not mapped and then you map it - since its already taking into account this.  We had to pick one value and we picked the best result you can get

hope this explains it.

rob
