### ISSUE TITLE
broken or missing translation strings

### ISSUE THREAD

**Issue by kmizole** [EDDiscovery/EDDiscovery#2885]
Hi, I noticed some strings which are not properly translated either because of a missing string or because it's simply missing.

These are the ones I pointed out (there's maybe more, as I don't have every event possible in my log). 

- Nav Route event : The event nave is not translatable, and the associated message is broken in tranlated languages (as shown below, the broken string that appears instead of "1 jumps" is in the je.tlp file line 627 : .InsuranceClaims: "Insurance Claims:;;N0" => "Droits à l'assurance:;;N0") repeated in french and german translation)
![navrouteEN](https://user-images.githubusercontent.com/598213/88279575-9acda680-cce4-11ea-9609-d29925c89f34.png)
![navrouteFR](https://user-images.githubusercontent.com/598213/88279586-9e612d80-cce4-11ea-858e-4af367a9fd3a.png)

- in FSS discovery scan event : the "bodies" string is not translated : 
![image005](https://user-images.githubusercontent.com/598213/88280079-7cb47600-cce5-11ea-89d4-43c8de56d836.png)

- in the Jump To event the  distance unit is not tranlated (it keeps ly) : 
![image007](https://user-images.githubusercontent.com/598213/88280172-a7063380-cce5-11ea-9aa5-d1d61f8ed35a.png)

- Problem with passenger mission translations : below are the different types of mission i found : 
![image009](https://user-images.githubusercontent.com/598213/88280365-f5b3cd80-cce5-11ea-91ff-1c1650b0076f.png)
![image011](https://user-images.githubusercontent.com/598213/88280370-fa788180-cce5-11ea-9e34-8f30ca8504ba.png)
![image013](https://user-images.githubusercontent.com/598213/88280377-ff3d3580-cce5-11ea-8ef8-ecc689102404.png)
![image015](https://user-images.githubusercontent.com/598213/88280385-0401e980-cce6-11ea-9701-de900f387a6e.png)
![image017](https://user-images.githubusercontent.com/598213/88280408-0d8b5180-cce6-11ea-950c-488c63f4d632.png)
![image019](https://user-images.githubusercontent.com/598213/88280427-12e89c00-cce6-11ea-9a7f-6fe5e56e3fcb.png)

- FSD charging event : Hyperspace string not translated (i didn't find any string for this one, so I think it's missing), and Supercruise neither
![image021](https://user-images.githubusercontent.com/598213/88280496-33185b00-cce6-11ea-8bc0-953c1f45feff.png)
![image027](https://user-images.githubusercontent.com/598213/88280652-7b377d80-cce6-11ea-8364-1ee9a747c9cb.png)

- Scanned Event : Cargo not translated
![image025](https://user-images.githubusercontent.com/598213/88280552-4e836600-cce6-11ea-9eda-b2cb48b40ee5.png)

- Limpets types does not seem to be translatable
![Limpet](https://user-images.githubusercontent.com/598213/88281438-f64d6380-cce7-11ea-8d63-6f36082a3f65.png)

- The mysterious case of the asteroid prospection events : translated strings appears in english but in the translated language you get a variable name : 
![AsteroidContent-EN](https://user-images.githubusercontent.com/598213/88281169-7c1cdf00-cce7-11ea-9fbe-48faeec251c3.png)
![AsteroidContent-FR](https://user-images.githubusercontent.com/598213/88281799-93a89780-cce8-11ea-8094-8cf5f996ae50.png)

**Comment by robbyxp1** [comment]
SECTION JournalNavRoute
.Jumps: "{0} jumps: " @

SECTION JournalFSSDiscoveryScan

.Progress: "Progress:;%;N1" @
.Bodies: "Bodies:" @
.Others: "Others:" @

ly is used widely, i'm not going to make that translatable.

Mission text is as supplied by Frontier - we don't have a translation for these set up as they are not known and can change by frontier.

FSD Charging event - 

SECTION JournalEntry

.Hyperspace: "Hyperspace" @
.Supercruise: "Supercruise" @

Scanned is just printed out as per Frontier data - not currently decoded 
Drone launch - again just print out the field..

The asteroid one - if we are translating, we do this.  That's because we don't want to print the frontier translation string (the the journal gives the variable and its localised string) since you've got the translator on. There are no lookups for this at present, so its unavoidable, and you get the logical name of the event.

I've updated the code with the ones we can do right now

**Comment by kmizole** [comment]
Great, i'll update the french files when i'll have some time :)

**Comment by robbyxp1** [comment]
thanks for the report.
