### ISSUE TITLE
Polonium rarity grade changed or wrong

### ISSUE THREAD

**Issue by shann112** [EDDiscovery/EDDiscovery#2897]
Hi there,
raw material polonium has rarity grade 5 (very rare) and can be collected only up to 100 ingame

best regards

good work with the app!!! thank u very much for this tool!

**Comment by iainross** [comment]
The collection cap for Polonium is 150.

The rarity listed in EDD maps onto the cap rather than the grade in game as the cap is not consistently aligned with the grade.  Grade 5 elements have a cap of 150 while manufactured has a cap of 100.  Grade 4 limits are all 150 except zirconium (250 for some reason).

**Comment by shann112** [comment]
thanks for the fast response,
just saw - after restart the game - that the cap is really 150. in the session before i collectet polonium for the 1st time and it showed me a cap of 100. seems to be a bug in ED not in EDDiscovery.

fly save :)
