### ISSUE TITLE
WebBrowser tool

### ISSUE THREAD

**Issue by nmyron** [EDDiscovery/EDDiscovery#2950]
Per this comment 

https://github.com/EDDiscovery/EDDiscovery/issues/2940#issuecomment-731693218

I was wondering if it would be possible to design a control to allow for a site to be loaded into a tab/grid/splitter in EDD. Similar to the way the EDSM pop-out operates to allow a user to see the full web site of EDSM in a pane, similar functionality could be added to allow EDD to load sites like Inara.cz, or Spansh.co.uk, or EDDB.io as tabs. 

Many commanders use the EDD tool, and many of these commanders also have to open additional browser windows to load these tools as described above for mining, resource location, and routing. If we could load them in as panes in EDD, this would likely help a great many commanders by reducing the need for alternate browser windows.

After reading the reply to my comment however, I also wondered if, being that IE 11 is scheduled for EOL, and the WebBrowser appears to use the IE-based Trident renderer might it future-proof things some to move onto EdgeHTML-based WebView controls?

**Comment by robbyxp1** [comment]
I can look into Webview.

As regards a general browser, i have resisted that due to security concerns.  

At the moment the EDSM browser only allows data from the EDSM web site to be accepted.  It does not allow browsing away from EDSM or data from other sites linked by EDSM.

As webbrowsers like Chrome/Edge/Firefox are constantly updated to beat potential hacks, my thoughts were that it was better for users who want to do general browsing to use those tools, and not an EDD webbrowser view.

So i'm not sure i want to get into this, with all the potential security issues a compromised web site inside EDD.

**Comment by nmyron** [comment]
What about adding browsers like EDSM that link directly to commonly used
tools like Spansh.co.uk, Inara.cz and Eddb.io, so that one would only be
able to load these specific web utilities, but like the EDSM browser, be
unable to navigate away from the targeted site?

Thanks

nmyron

**Comment by robbyxp1** [comment]
I'll move this to project suggestions. Thanks

**Comment by robbyxp1** [comment]
Going to be in 11.9.3
