### ISSUE TITLE
Surveyor panel not updating.

### ISSUE THREAD

**Issue by metalsynkk** [EDDiscovery/EDDiscovery#3022]
Sometimes it loads fine, sometimes it will stop working for hours on end. Read somewhere that switching to FSS and back fixes it, or switching UI panels in-game, but to no avail. Restarting EDD doesn't help. Switching commanders does, but I don't really feel like doing that every new system, as an explorer.

Sorry if this has been reported/closed somewhere already but from what I could gather I didn't see anyone with a similar issue. It's not a terrible issue, since Estimated Values and Scan do update properly. But just a small hindrance.

**Comment by Eahlstan** [comment]
There was a bug regarding the 'jump to newest entry' task that would cause this behaviour.
This has already been fixed (currently available in the beta).
If your bug is the same you can make it work by either starting EDD showing the history tab (by switching to the history tab before closing) or by switching to the history tab when it happens and manually selecting the newest entry. This will kickstart the jump task and you can switch to other tabs again.

**Comment by robbyxp1** [comment]
As above, thanks.

**Comment by metalsynkk** [comment]
> 
> 
> There was a bug regarding the 'jump to newest entry' task that would cause this behaviour.
> This has already been fixed (currently available in the beta).
> If your bug is the same you can make it work by either starting EDD showing the history tab (by switching to the history tab before closing) or by switching to the history tab when it happens and manually selecting the newest entry. This will kickstart the jump task and you can switch to other tabs again.

Yup, this did the trick. Thank you!

**Comment by robbyxp1** [comment]
it will be fixed in 12.0, expected next week
