### ISSUE TITLE
Bookmarks on History Panel Crash

### ISSUE THREAD

**Issue by WiseNat** [EDDiscovery/EDDiscovery#3048]
### Description
On the history tab, I changed the "Nearest Stars" panel to Bookmarks - the app crashed afterwards. Elite dangerous isn't currently open and I do have bookmarks; the bookmarks tab works normally outside of this.

### Exception Details:
>EDDiscovery v11.10.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: This operation cannot be performed while an auto-filled column is being resized.
>   at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
>   at System.Windows.Forms.DataGridView.SetColumnHeadersHeightInternal(Int32 columnHeadersHeight, Boolean invalidInAdjustFillingColumns)
>   at System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight(Boolean fixedRowHeadersWidth, Boolean fixedColumnsWidth)
>   at System.Windows.Forms.DataGridView.OnColumnHeadersGlobalAutoSize()
>   at System.Windows.Forms.DataGridView.set_TopLeftHeaderCell(DataGridViewHeaderCell value)
>   at System.Windows.Forms.DataGridView.get_TopLeftHeaderCell()
>   at System.Windows.Forms.DataGridView.OnCellMouseEnter(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
>   at System.Windows.Forms.DataGridView.OnColumnWidthChanged(DataGridViewColumnEventArgs e)
>   at System.Windows.Forms.DataGridView.AdjustFillingColumns()
>   at System.Windows.Forms.DataGridView.ComputeLayout()
>   at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
>   at System.Windows.Forms.DataGridView.OnHandleCreated(EventArgs e)
>   at System.Windows.Forms.Control.WmCreate(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
That is a very odd stack trace:
* System.Windows.Forms.Control.WmCreate -> the window or control was created
* [System.Windows.Forms.DataGridView.OnHandleCreated](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,15728)
* [System.Windows.Forms.DataGridView.PerformLayoutPrivate](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,20264)
* [System.Windows.Forms.DataGridView.ComputeLayout](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,4448)
* [System.Windows.Forms.DataGridView.AdjustFillingColumns](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,968)
* [-- Not in stack trace --](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewBand.cs,847)
* [-- Not in stack trace --](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,11630)
* [System.Windows.Forms.DataGridView.OnColumnWidthChanged](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,14983)
* [System.Windows.Forms.DataGridView.UpdateMouseEnteredCell](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,29219) -> you had your mouse over the table when it was being created
* [System.Windows.Forms.DataGridView.OnCellMouseEnter](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,12931)
* [-- Not in stack trace --](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,7204) -> (row, col) == (-1, -1)
* [System.Windows.Forms.DataGridView.get_TopLeftHeaderCell](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridView.cs,5139) -> top-left header cell did not yet exist
* [System.Windows.Forms.DataGridView.set_TopLeftHeaderCell](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridView.cs,5161)
* [System.Windows.Forms.DataGridView.OnColumnHeadersGlobalAutoSize](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,14397)
* [System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,1777) -> The column headers had not yet been resized
* [System.Windows.Forms.DataGridView.PerformLayoutPrivate](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,26815) -> AutoSize was not set
* [System.Windows.Forms.DataGridView.PerformLayoutPrivate](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewMethods.cs,20250) -> Because it was in System.Windows.Forms.DataGridView.AdjustFillingColumns

It looks like a DotNET framework bug, where if you have your mouse over the top right cell, then it will error out while creating the grid view
(why does that sound familiar)
https://github.com/EDDiscovery/EDDiscovery/issues/1487

It looks like whichever control this is doesn't have that workaround.

**Comment by robbyxp1** [comment]
Going to be fixed in 12.0, thanks for the report.
