### ISSUE TITLE
Add to... works on the main history tab but not on other history grid tabs.

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3105]
Title says it all.
If (single or multiple) entries are selected on the main history tab the "Add to..." context menu options work just fine, but the same thing doesn't do anything if working with a seperate history panel.

**Comment by klightspeed** [comment]
The `OnNewStarList` event probably needs to be pushed up to the main form / controller, and the controls subscribing to that event probably need to subscribe to that event on the form / controller instead of the main travel history control.

**Comment by robbyxp1** [comment]
I'll have a look, but lets not change anything about this at the moment - need to bring everything back together first and release a new version.

**Comment by robbyxp1** [comment]
Working as intended.  The panels attach to the nearest travel history type panel (journal/history/starlist) and listen to its star list updates., and attach to one history grid only.

This is because if the panel was in a splitter or grid, you would expect a push from the history panel of that grid to apply only to the sub panels in that grid.
