### ISSUE TITLE
Estimated scan values sorting is wrong in linux

### ISSUE THREAD

**Issue by matt32106** [EDDiscovery/EDDiscovery#3176]
I don't know if it's OS dependent or regional settings dependent but the sorting of the values in the estimated scan value panel is wrong. It sorts alphabeticaly instead of by the value represented by the string. 
https://i.imgur.com/KYHDreQ.png
Ubuntu 20.04
EDDiscovery commit from 5-6 jours ago.
Mono JIT compiler version 6.12.0.122

**Comment by klightspeed** [comment]
Given that the column(s) in question are formatted as `Number / Number` (which cannot be parsed as numbers without extra processing), the values would have to be split on the `/` and trimmed before trying to parse them as numbers.

**Comment by robbyxp1** [comment]
The code is stripping out the /.. and sorting on the first number (e.SortDataGridViewColumnNumeric() does this).

I've just clicked on Mapped and its doing it in the right order.

**Comment by robbyxp1** [comment]
This may be a linux issue.

**Comment by robbyxp1** [comment]
It looks like mono never is calling         private void dataGridViewEstimatedValues_SortCompare(object sender, DataGridViewSortCompareEventArgs e)

this is a mono issue, and at the moment, it is what it is.  I can't see it anywhere calling OnSortCompare, etc.

**Comment by robbyxp1** [comment]
I will close this tomorrow, we probably can't fix it.

**Comment by matt32106** [comment]
Are you going to report it upstream?

**Comment by robbyxp1** [comment]
There is no point. There is no-one maintaining mono-winforms. I've looked in the past and reported bugs and nothing gets done.

It is what it is.

Yes the sorting works perfectly on windows, even with commas, so its a mono issue.

**Comment by matt32106** [comment]
Hmm, what is strange is that the sorting is OK in the columns that don't have "/" even when there values both < and > to 1000.
In the columns with "/" it sorts in string order.  I don't understand why there would be a difference between the two if the stripping out operation leads to variables of the same type. Do you?

**Comment by robbyxp1** [comment]
There is no evidence of sort compare being called in mono, so custom sorting can't be done.  I've double checked this morning.

There is nothing i can do about this, its just a feature of running mono.

Now closing.

**Comment by klightspeed** [comment]
Getting sorting working properly under mono would involve submitting a patch to mono to fix [`DataGridView.Sort(DataGridViewColumn, ListSortDirection)`](https://github.com/mono/mono/blob/main/mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridView.cs#L3059-L3105) and [`DataGridView.ColumnSorter`](https://github.com/mono/mono/blob/main/mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridView.cs#L6583-L6625) to use `OnSortCompare`, falling back to the default comparison if that doesn't handle the sort.

Trying to implement the fix on our side would involve far too much reflection voodoo.

Numeric sorting works "as expected" because Mono's implementation of DataGridView.Sort probes the data to see if it's numeric before sorting it.

**Comment by robbyxp1** [comment]
Re my point above about the lack of Mono Winform attention.  No point.

**Comment by matt32106** [comment]
OK. Thanks for your time.
