### ISSUE TITLE
There was an unhandled UI exception.

### ISSUE THREAD

**Issue by rhadkins2002** [EDDiscovery/EDDiscovery#3191]
I've updated to the latest release and remain to get this error even though I thoroughly deleted the prior version.

### Exception Details:
>EDDiscovery v12.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlMiningOverlay.Display(HistoryEntry he) in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:line 142
>===== END =====
>```

**Comment by klightspeed** [comment]
It needs to check that you are in a ship - the location of the error suggests that `HistroyEntry.ShipInformation` is null, which can happen if you loaded into the game in a SRV or on-foot.

**Comment by robbyxp1** [comment]
It can happen if the only journals you have are in an SRV.. or you've limited the reading of the journals so the same is true, otherwise ShipInformation is set up by previous journal entries.

Went thru all uses of ShipInformation and checked their protection.  Updated the 3dmap branch as thats going to be merged soon.

Thanks for the report.
