### ISSUE TITLE
Screenshot conversion fails

### ISSUE THREAD

**Issue by frikinevil** [EDDiscovery/EDDiscovery#32]
LOVE this app!  Unfortunately when convert images is selected, all conversion fail. Tried all formats 
Hi-res snapshot: Exception in imageConvert:Parameter is not valid
standard res snapshot: Exception in imageConvert:A generic error occurred in GDI+
 
Resolution is 4k. (3840 x 2160)

Couldn't find any logs to provide more info.  Please let me know if there is anything else I can do to assist.

My Specs:
i5 4660
16gb DDR3
Windows 10 Home
Nvidia GFX 970 (4gb)

Great App, and keep at it sir!

**Comment by Aterfax** [comment]
I can confirm this, standard screenshots convert nicely but Alt-F10 high resolution images cause an out of memory error and cannot be processed.

**Comment by Red13x3** [comment]
I have a question about this screenshot functionality, which I've never been able to make work to date:

Can it ONLY work with screenshots made by ED using f10, or can it work with ANY screenshots taken by another application? What is the qualifier.

All I would want out of this functionality is renaming the file I create to the system name and maybe (pre-)appending a time stamp.

Can someone explain why it is doing file conversions? Isn't that what the screenshotting app should control?

--
Mark
iPhone: 0402 322 901

**Comment by Aterfax** [comment]
I believe it is intended to work directly from the screenshot method in 
ED since it asks for the folder, i.e. only does a conversion when you 
take the screenshot as it sees a new file being saved. This should work 
for F10, normal ED screenshot and Alt-F10, high res ED screenshot. It 
should save with the system name and timestamp when it converts the 
bitmap into the filetype of your choice.

The reasoning for the conversion I believe is that ED saves into the BMP 
image format which is not lossy but has a very high footprint (saved 
file size) compared to other formats like JPEG (lossy format) or PNG 
(not lossy format but better at compression.)

**Comment by Gerdofal** [comment]
I also get this error on standard convert:

Exception in imageConvert:A generic error occurred in GDI+

**Comment by gregmalcolm** [comment]
I think there have been some improvments on how screenshots are managed in recent versions. Anyone still seeing the issue?

**Comment by robbyxp1** [comment]
Extensively tested. 4.1 adds more checks for file prescense before conversion.
