### ISSUE TITLE
Transparent text readability

### ISSUE THREAD

**Issue by klightspeed** [EDDiscovery/EDDiscovery#3208]
Is there anything that can be done to make the text box more readable in game?  Is it a Windows thing that the text becomes readable only if you hover the mouse over the box, or place a white background behind the window (such as using an empty *.txt file?  I have found that if I hover my mouse over the box I can read it in game but it is hard to play that way.  For example, clicking a mouse button to fire my weapons while the cursor is over the text box causes windows to focus EDD instead of the game, effectively alt-tabbing me out of the game.  And of course, focusing an *.txt file to make it readable also alt-tabs me out of the game.

_Originally posted by @JamesRabe in https://github.com/EDDiscovery/EDDiscovery/issues/2969#issuecomment-986254891_

**Comment by klightspeed** [comment]
@JamesRabe what colour do you have the foreground text set to in the Settings tab -> Theme -> Edit Theme?

**Comment by robbyxp1** [comment]
Please read https://github.com/EDDiscovery/EDDiscovery/wiki/Using-Panels for controlling transparency and form control.

A video on this is https://youtu.be/fSnxTDL90B4?t=452

**Comment by JamesRabe** [comment]
Thanks for the info Rob but the hearing-impaired text box isn't an EDD pop-up window or panel so it doesn't seem to have those functionalities. If I am wrong I'd love to shown how to access them.
    On Monday, December 6, 2021, 03:35:27 AM CST, Rob ***@***.***> wrote:  
 
 


Please read https://github.com/EDDiscovery/EDDiscovery/wiki/Using-Panels for controlling transparency and form control.

A video on this is https://youtu.be/fSnxTDL90B4?t=452


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JamesRabe** [comment]
II am using Windows default but changing the theme does not change the appearance of the hearing impaired text box.

Sent via the Samsung Galaxy A51 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robbyxp1** [comment]
Ahh, that was not clear from the comment above, because it got moved to a new thread.

The dialog is in the default font size for the system (set by themeing in settings) and can't currently be changed independently.  I would have to think how to do that.

**Comment by robbyxp1** [comment]
Added to project list.
