### ISSUE TITLE
Microseconds in timestamps 

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#3283]
Here at [Trade Dangerous](https://forums.frontier.co.uk/threads/trade-dangerous-est-2015-power-users-highly-configurable-trade-optimizer.441509/) Central, we had been recently experiencing some nasty crashes with our server. 

After some digging we found that now and again, at most once or twice a day, a client was sending trade information to EDDN with timestamps that included microseconds and our db simply wasn't expecting this. Indeed in the 7 years we've been operating, it's never been even something we needed to consider. Well, ok - we added a bit of code to deal with that, and also some to satisfy our curiosity as to where these very rare (1 in 1000s of messages) came from.

Finally one has popped up that we've been able to catch. We were expecting it to be from one of the tiny clients way down on the list on the EDDN status page, so imagine our surprise when we logged that 
"Client EDDiscovery, version 15.0.4.0, uses microseconds."

I'll try and add some more code to catch another and get more detail on the exact message which did this, I wasn't expecting it to be a big player, so didn't really care, but I as I used EDDiscovery myself, I'm suddenly more invested. I'll add any additional information I get below.

**Comment by klightspeed** [comment]
Both `EDSM - Console` and `EDDiscovery` are including the millisecond and `Z` timezone in the `.message.timestamp` for CAPI-sourced non-journal messages (i.e. commodity / shipyard / outfitting)

**Comment by Tromador** [comment]
I see. Amazed we could run at all, I can only assume that EDMC doesn't include partial seconds and drowned out EDDiscovery schema in our aggregator. To be clear, we are only interested in commodity schema, so I doubt EDSM would affect us.

Out of interest, how long has EDDiscovery been doing this? Was there a particular reason? The example schema in the [EDDN documents](https://github.com/EDCD/EDDN/blob/live/docs/Developers.md) don't include partial seconds. (e.g.   "timestamp": "2019-01-08T06:39:43Z").

As it is we are fine now, and I guess you are saying from the point of view of EDDiscovery "working as intended", but I would be grateful if you indulged my curiosity. Maybe partial seconds should be used and perhaps EDDN need to somewhat more clearly specify the expected timestamp format so we are all on the same page.

**Comment by klightspeed** [comment]
This was introduced in https://github.com/EDDiscovery/EliteDangerousCore/commit/f70b62f3848a6d2ae2590a1010b363659cf8e14b#diff-8cb52f0f1ee03c985eb88e7bb0c57d9f5665b7018881e5ef1057ba16c176e888, which was included in 15.0

Robby probably forgot that events generated from CAPI shipyard / market endpoints use `DateTime.UtcNow` and as such include fractions of a second.

**Comment by Tromador** [comment]
Okay, given that 
EDDN specifies ISO 8601
The iso makes provision for including fractions of a second, but makes it clear that the "number of decimal places needs to be agreed to by the communicating parties".
Based on the EDDN documentation, EDDN has agreed to the use of 0 decimal places.
And "Robby probably forgot"

Is this in fact not working as intended and a bug?

**Comment by eyeonus** [comment]
I sincerely appreciate your help in locating a bug in my code that had been perplexing us for pretty much the entirety of the code's deployment on Trom's server. I'm happy to report that it has resulted in my code becoming much more stable, in that we no longer seem to crash every other day or so.

;-)

**Comment by robbyxp1** [comment]
Well, the cat is out of the bag, and you'll all have to deal with microseconds in the messages. 

Its not much point fixing anything, since the code is out in the wild and can't be shut down.

Where in the EDDN docs does it specify no milliseconds? This does not : https://github.com/EDCD/EDDN/blob/master/schemas/README-EDDN-schemas.md

**Comment by eyeonus** [comment]
It does not explicitly state "don't use microseconds", no, however, it does state quite clearly that must be in the  ISO8601 format:

https://github.com/EDCD/EDDN/blob/master/schemas/README-EDDN-schemas.md#general-eddn-message-outline
> Each message object must have, at bare minimum:
> 
>  1.   timestamp - string date and time in ISO8601 format.

The format specified does have a provision for using partial seconds, but states that the "number of decimal places needs to be agreed to by the communicating parties". In other words, the default should be 0, and any more precision than that needs to be known about and agreed upon by all parties involved in the communication.

TD has agreed to a precision of 0. The example provided by EDDN for their schemas, which is stated by them to be the official specification, also has a precision of 0. Since TD doesn't crash from the ultra-precise timestamps anymore, feel free to not fix this if you're feeling too lazy to bother, I totally get it, this is super minor.

But "it's out in the wild" is a horrible reason to not fix a bug, dude. You release updates to this thing to fix code that is "out in the wild" all the time. We all do, that's literally the definition of code maintenance.

**Comment by robbyxp1** [comment]
Thanks for the tips of how to write and maintain software.  

EDDN does not stipulate that milliseconds is not allowed. ISO8601 says that you can have decimal fractions. 

Its within spec.

Closed.

**Comment by eyeonus** [comment]
You're welcome. Thanks for being a dick.

**Comment by robbyxp1** [comment]
I thought you would come back with something like that.  Please don't come anywhere near here again, or EDCD. I'm not going to tolerate people being rude.

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDDN/blob/master/schemas/README-EDDN-schemas.md#general-eddn-message-outline has now been updated to be explicit about this:

> 1. timestamp - string date and time in ISO8601 format.
>
>    1. Whilst this technically allows for any timezone to be cited you SHOULD provide this in UTC, aka 'Zulu Time' as in the example above. You MUST ensure that you are doing this properly. Do not claim 'Z' whilst actually using a local time that is offset from UTC.
>    2. Historically we had never been explicit about if Senders should include sub-second resolution in the timestamps, or if Listeners should be prepared to accept such. As of 2022-06-24 we are explicitly stating that Senders MAY include sub-second resolution, and Listeners MUST be prepared to accept such.

**Comment by Tromador** [comment]
Wow. I know I was a bit tongue in cheek about this from the start but didn't want or expect to devolve into open hostility. I'm saddened to see this. 

I think we have the correct resolution which is a tighter spec from @Athanasius

**Comment by robbyxp1** [comment]
I've no trouble with what you Tromador said.  As to the other guy, coming on here being passive aggressive does not get people to do things for you, especially as EDD was not violating any requirements.

**Comment by klightspeed** [comment]
Just for some context, `Elite G19s Companion App` has been sending commodity / shipyard / outfitting events with microsecond timestamps since at least 2018.  I am going through my archives , but at least `EDAPI Trade Dangerous Plugin` and `EDCE` also sent commodity / shipyard / outfitting with microsecond timestamps, and `EDAPI Trade Dangerous Plugin` also sent events using a non-zulu timezone.

**Comment by Tromador** [comment]
I have to disagree. EDDiscovery was out of compliamce. You may argue that it's a technicality, but ISO, RFC and similar documents all have the devil in the detail.

The point we both made was that although iso8601 allows for partial seconds (no argument there) it ALSO requires that communicating parties agree on their use. 

Sans agreement, no partials and prior to the change in the EDDN spec there was no implied or explicit agreement between such parties to use partial seconds. 

In a popular TV show from the 80s a character notes that the instructions for their video recorder do not say not to put washing up liquid into it, with comedic results. Point being, just because a thing is not expressly denied, doesn't mean that it is allowed. 

Similarly fact that EDDN did not ban partial seconds did not mean they were permitted, in fact given the on site examples were all in only complete seconds, there was no basis to assume any agreement between communicating parties to use partial seconds

So. I don't condone the name calling, but I have to agree with eyeonus interpretation of the spec. 

All of which said, the EDDN docs have been clarified, so EDDiscovery and anyone else using partials are now compliant and as you said above, the cat left the building, and so it's long since been a moot point.

**Comment by Athanasius** [comment]
No, EDD was not out of compliance.

EDDN has never explicitly defined the timestamp format, beyond the reference in the schema files to the upstream defined format, which if you follow the chain ends in "ISO 8601".  I improved the documentation to be explicit about the desire for UTC, not any other timezone, and now to be explicit about fractional seconds being allowed.

In the absence of an explicit agreement all Senders were free to add microseconds or not, and all Listeners *should* have been prepared to handle messages with or without them.

No, "the way things happen to have done it until now" doesn't constitute an agreement.

If we're going to get all rules-lawyery about this then:

1. ISO8601 allows for either `.` (full stop) or `,` (comma) as the separator before the fractional part.
2. ISO8601 allows for using a fractional part to the lowest order part of a timestamp, no matter what it is.  It doesn't need to be seconds, i.e. `2022-06-25T15:30,5` is valid.

This just emphasises that Listeners should, where possible, use a well-written and tested library function to parse these timestamps, rather than attempting the parsing themselves, whether that be with `strptime()` or something else.

Dates and times are one of those things with enough caveats, corner cases and general gotchas that you should be leaning on the work of others rather than doing it from scratch yourself.

I'll also note that we also have no guarantee that Frontier won't change the Journal timestamp format in some manner.  They could add fractional seconds, including accidentally using locale-dependent separator if they do.

Now, can we finally just bury this horse rather than further beating it ?

**Comment by Tromador** [comment]
If Frontier did a thing it wouldn't necessarily make them right, just that we'd all have to live with it.

I say without permission to do the thing, you shouldn't do the thing.
You say without forbidding the thing, allow for people doing the thing.

Tomayto, tomarto?

Yes. I have had enough too.
