### ISSUE TITLE
Route Finder exception

### ISSUE THREAD

**Issue by tecnosegugio** [EDDiscovery/EDDiscovery#3319]
Was trying to trace a route from "Whano BM-K d9-0" to "Beagle Point" with 60LY jump length.

An unhandled fatal exception has occurred.

==== BEGIN ====
System.ArgumentNullException: Il valore non può essere null.
Nome parametro: source
   in System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   in EliteDangerousCore.RoutePlotter.GetBestEDSMSystem(Point3D currentPosition, Point3D travelVectorPerLy, Single maxDistanceFromWanted, Single maxRange) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\RoutePlotter.cs:riga 158
   in EliteDangerousCore.RoutePlotter.RouteIterative(Action`1 info) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\RoutePlotter.cs:riga 86
   in EDDiscovery.UserControls.UserControlRoute.RoutingThread(Object _plotter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:riga 494
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart(Object obj)
===== END =====

**Comment by Eahlstan** [comment]
Thanks for the report.
This is already fixed in the code (see https://github.com/EDDiscovery/EDDiscovery/issues/3310 ).
It's caused if you're hitting the EDSM query limit, until a new version with a fix is out (though this fix only handles the crash and can't do anything about the limit) having your own systems DB by enabling the star data download on the settings panel (only do if you're using an SSD) and deactivating the EDSM query on that panel (there's a button labeled "EDSM") is the only way to have that panel working without crashes for really long routes.

**Comment by tecnosegugio** [comment]
Confirmed!

Disabling "EDSM" button in Route Finder everything works.

Thank you.
