### ISSUE TITLE
New version or no new version?

### ISSUE THREAD

**Issue by BannorPhil** [EDDiscovery/EDDiscovery#3348]
![image](https://user-images.githubusercontent.com/37474684/205088133-2a0ed408-57d4-478f-84a4-4668ec22f3ce.png)

**Comment by robbyxp1** [comment]
Thanks for the report. We know, the next version will be out shortly today.

**Comment by Eahlstan** [comment]
Basically the check is wrong. There's already a new version out that the check doesn't find due to an error in the version string.
But as Robby said: A new new version will be out soon that will be findable by EDD itself. So either wait for that version or go to the release site here and download 16.0.0
