### ISSUE TITLE
FR: Filter organic scans by 'sold' or by time

### ISSUE THREAD

**Issue by Greymagic27** [EDDiscovery/EDDiscovery#3419]
Currently if I sell on the same day as scanning more lifeforms, this will skew my results to how much I have earnt. This could be fixed by adding a time filter, or by allowing 'sold' data to be filtered out

**Comment by Eahlstan** [comment]
@robbyxp1 As we're on improving the [Organics panel](https://github.com/EDDiscovery/EDDiscovery/issues/3418) might it be possible to copy the docking date filter from the statistics panel to the organics?

**Comment by Eahlstan** [comment]
@Greymagic27 If you're only interested in the value you can use the Travel subpanel of the statistics panel to either use the "Last dock" column to see your value since your last dock
![Screenshot 2023-05-27 190055](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/168f720e-f545-46e6-981d-7192adc5b89b)
or use the docking date selector to set the start (and end) date to a docking event of your choice.
![Screenshot 2023-05-27 190137](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/b3bcd324-b561-4f5f-a384-158154618a14)

**Comment by Greymagic27** [comment]
Thanks for showing me this. That's useful. If I ever sell part way through the day I'll make sure to check that!

**Comment by robbyxp1** [comment]
Moved to worklist
