### ISSUE TITLE
Strange behaviour after deleteing cmdr

### ISSUE THREAD

**Issue by dymm2000** [EDDiscovery/EDDiscovery#3489]
I did deleted the cmdr in settings. After that EDD had strange behavior:
-not able to recreate cmdr with rereading all logs like it do it after fresh install - auto read name and journals
-does reread all logs into "hidden logs cmdr"
-after "reset all history" recreates cmdr, but still load all journals to "hidden log" (may be I did something more, I do not remember, but behavior was such as described)

only helps delete user db and recreate all from the scratch.

**Comment by Eahlstan** [comment]
If you delete commanders in the settings you're telling EDD that you don't want to see it ever again, hence the events linked to it now are linked to nothing and thus only visible in the hidden log. The events are still in the DB and thus rereading has no effect.
Not a buh.

**Comment by dymm2000** [comment]
How to recreate cmdr without delete db? Since this db also contains general UI settings

**Comment by klightspeed** [comment]
If I recall correctly, the delete is a soft delete (i.e. setting `Deleted=true`).  Deleting a commander shouldn't immediately move all history entries from that commander ID to the hidden logs commander ID, and unless and until you perform other actions undeleting them should only require setting Deleted=0 on that commander in the database.

"Reset all history to current commander" will have moved all history to the current commander, regardless of what commander it was linked to beforehand.

Fortunately resetting the commander ID on the journal entries does not reset the commander ID on the travel log units (i.e. references to journal files). This does present a potential lifeline:
1. Close EDDiscovery
2. Take a backup of the database
3. Open the database in e.g. DB Browser for SQLite
4. Set the Commander Deleted to false
5. Update the CommanderId on the journal entries back to the CommanderId on the travel log units

Or you could take the nuclear approach, and:
1. Close EDDiscovery
2. Take a backup of the database
3. Open the database in e.g. DB Browser for SQLite
4. Truncate both the Commanders and TravelLogUnit tables
5. Re-open EDDiscovery
6. Re-read ___all___ of your journals

**Comment by Eahlstan** [comment]
> If I recall correctly, the delete is a soft delete (i.e. setting `Deleted=true`). Deleting a commander shouldn't immediately move all history entries from that commander ID to the hidden logs commander ID, and unless and until you perform other actions undeleting them should only require setting Deleted=0 on that commander in the database.

This seems to be a rare case of you misunderstanding the issue.

This user wiped his EDSM data (on the website), wondered why EDD didn't resync every single event (how should EDD know EDSM was wiped?), then deleted the commander in the settings panel (which only "hides" the commander) then got angry that EDD didn't reread his journals (because of course they are still in the DB) finally nuked his DB (because in the version of the wiki at this time "delete commanders & journals" wasn't mentioned - only "delete journals" was - which doesn't seem to be enough to even open the safe mode menu for this user (if he even read that thing)), rebuilt the user DB, saw that in EDD everything was alright but on EDSM it wasn't, got angry again and blamed EDD for either an EDSM error or his impatience to let EDD finish syncing to EDSM. Unfriendly issue spam instead of a civil help request.

There never was an EDD error, nor was there a request for undeleting a deleted commander. But yes: It's just "Deleted = 1" in the `Commanders` table, so it's easy to "restore" it by editing that field in the DB.

**Comment by Eahlstan** [comment]
Not that there isn't an issue involved: EDD gracefully crashes when deleting the currently active commander, but that wasn't even mentioned in any of the issues.
