### ISSUE TITLE
Gravity doesn't show properly on organic scans menu

### ISSUE THREAD

**Issue by Greymagic27** [EDDiscovery/EDDiscovery#3491]
The gravity number does not display properly on the organic scan menu.

Currently the planet I am on is 0.04G as confirmed ingame, but on EDDiscovery it displays as 0.0G
![image](https://github.com/EDDiscovery/EDDiscovery/assets/46166848/aa3ca52f-e082-4f56-b21b-4f269352e741)

This does not change when landed on the planet, in SRV, on foot or after scanning a bio signature.
Rescanning all journal files also did not solve this issue

**Comment by Eahlstan** [comment]
That's because it's only displayed to one digit after the decimal point.
That's not a bug, it's working as intended. Especially in this place it's only meant to be a quick and dirty way to see if landing on that body is difficult or not.
If you want to see a more precise value you can see it on the history grid, the journal panel, the scan panel, ...
And if you want to see most precise value possible you can right click on the scan event on the history panel and click "copy to clipboard/log" to see the raw event in EDDs log - which contains gravity with 6 digits after the decimal point.

**Comment by Eahlstan** [comment]
I did propose a change to make it impossible to show zero gravity and improve the precision. Let's wait and see what Robby thinks about [this](https://github.com/EDDiscovery/EDDiscovery/pull/3493).
