### ISSUE TITLE
Surveyor Scan Value Inaccuracies

### ISSUE THREAD

**Issue by AmericanJimmy** [EDDiscovery/EDDiscovery#3579]
This is an issue with the surveyor overlay. I am updated to current version 18.0.9.0. Don't have too many specifics since it's not an error message or anything so I'll try to explain as best I can:

- Doing R2R, went to system scanning body A 5 with FSS, value listed at around ~1,000,000 cr
- Scan body with DSS, where the value jumps up to over 4,000,000 cr once mapped
- Take data to station, Universal Cartographics lists system data as 775,000 cr.

I understand if estimated system values are not exact, but give or take 500% seems less like an estimate and more like a bug.

Also I've been using EDDiscovery for multiple years now and this is the first time I recall this happening, granted it's been a few months since I've played so I very well could be misremembering.

I'd be happy to give more information if needed.

**Comment by Eahlstan** [comment]
> Doing R2R, went to system scanning body A 5

Which system?

> Scan body with DSS, where the value jumps up to over 4,000,000 cr once mapped
> Take data to station, Universal Cartographics lists system data as 775,000 cr.

Values shown in UC are without any first discovery bonus, those get added when selling. Don't look at the bonus pop-up too, it's been bugged since forever.
The only way to see how much money you actually got is to look at the journal event.

Additionally: If it was a body in the bubble forget every value by every tool and everything you see in game or in the journal. (Some) Bubble bodies are impossible to calculate and even the game tosses out different amounts on different stations and on different times.

That said I have to add: I mapped and sold two unmapped bodies yesterday and got no bonus at all. I'm currently searching for confirmations of this behaviour, so there might be something odd in game.

**Comment by AmericanJimmy** [comment]
> Which system?

18 Comae Berenices A 5, scan value 304602 cr, mapping value 1106719 cr according to Spansh.

> Additionally: If it was a body in the bubble forget every value by every tool and everything you see in game or in the journal. (Some) Bubble bodies are impossible to calculate and even the game tosses out different amounts on different stations and on different times.

Good to know, thought I'd ask anyway since I've personally never seen it before and the game updated which could have broken some stuff.

**Comment by Eahlstan** [comment]
> 18 Comae Berenices A 5, scan value 304602 cr, mapping value 1106719 cr according to Spansh.

That's a bubble body, sadly there's no way to correctly predict them.

**Comment by Eahlstan** [comment]
Additional info: There are actually two things involved in your exact scenario.

First: the inability to predict the value of certain bubble bodies. It affects those that have no first discoverer, but a first mapper. (The first discoverer is hard coded to be impossible to get.)
We coded those bodies to be predicted way too low in most cases - that's why it was listed as being worth about 1,000,000 credits when you first scanned it.

Second: When scanning a body (most likely by using the FSS) a scan event gets written to the journal. Regarding those bodies the first received event correctly informs us that the body has no first discoverer, but a first mapper. After probing those bodies a second scan event gets written to the journal. Normally it is a exact copy of the first event. Sadly at those hard coded "no first discoverer" (and on the few "no first mapper" bodies too) those flags change to the wrong "no first discoverer and no first mapper yet" values. Thus the "this is a cursed bubble body" detection fails and the predicted value skyrockets - in your case to about 4,000,000 credits.

So when you're in the bubble keep in mind that the first shown maximum value is the "correct" one.

**Comment by AmericanJimmy** [comment]
Good to know. Thank you.
