### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by HairballHacker** [EDDiscovery/EDDiscovery#5]
It seems when the app first tries to load the AppConfig.xml, if it cannot find it, it creates a null object reference error in red on the screen. I have to manually specify the path. I think the auto-detect feature could be made smarter by knowing about Steam installs (which I have). For the the correct path is 

C:\Program Files (x86)\Steam\SteamApps\common\Elite Dangerous\Products\FORC-FDEV-D-1010

Obviously, the app should look for this path on all mounted drives, not just C.

**Comment by Majkl578** [comment]
It's not easy to *guess* the location this way, since Steam allows users to have multiple locations (called *Steam Library Folders*).
But I think we could look for E:D in Windows Registry.
For Steam version of E:D, there should be `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 359320` with `InstallLocation`.
For non-Steam version, I have no idea right now as I don't have access to such version.

**Comment by AnthorNet** [comment]
On windows 8/64 bits:
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{696F8871-C91D-4CB1-825D-36BE18065575}_is1 for the launcher with '''Inno Setup: App Path'''
=> Nothing for the game... And not located in Launcher directory.
The game is located here: C:\Users\AnthorNet\AppData\Local\Frontier_Developments\Products\FORC-FDEV-D-1010

On my other box win7/64 bits, it is a different path, will check.

**Comment by Majkl578** [comment]
By the way, I believe the null dereference should be fixed by ace20a85c78bdadb7c4b7b2f045b1d1c44f2a2a8.

**Comment by AnthorNet** [comment]
Registry on Win7 is the same, game installed in launcher path.

**Comment by finwen** [comment]
Is this problem gone now?
