### ISSUE TITLE
Small usability fixes

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#623]
Hi to all! EDDsicovery is getting better and better each pull, so awesome!
I'd like to ask if anyone else feel the needs of small improvement in the usability fields, ad those:

1) decouple scan window to S-Panel.
I love it, and extensively use, but I found extremely difficult to properly position it in the screen. I usually prefer a small S-Panel window, just with my target highlighted and some - three or so - last systems displayed, on the left corner of the screen. So, when the discovery scan details pop out, they usually are weirdly over some other details, especially if I need to open the galaxy map.
If it be decoupled - another Transparent Scan Details poput... - I can position it much lower, or at the other side, under the trip panel. Could it be?

2) How about if EDDiscovery could see the journal's when we mark a route, to update the target of the route? As it's now persistent - when we logoff and logon, if we open the galaxy map ED remember it - so I think that it's marked in the journal. It could be highlighted in the S-Panel as a waypoint...

Thanks to all!

**Comment by iainross** [comment]
I whacked the s-panel scan in pretty quickly cos I really, really wanted it but I didn't want to spend too much time because I know @robbyxp1 is planning on an overhaul in the not too distant future.  You're not the first person to ask though, so I might split it out, I'll check with Robby how imminent the overhaul is...

Plotting a route does not trigger a journal entry I'm afraid so there's not anything we can hook into there (or at least not one that's included in the documentation, I can double check when I'm back at my gaming box but I'm not optimistic).

**Comment by andreaspada** [comment]
Well, thanks for your kind reply! I really appreciate your effort, so 
take your time. I'm glad that other player felt that need, and of course 
I know that an overhaul is maybe more urgent that anything else, which 
may address many usability issues; and, between us, the interface is 
soooooooooo slow to redraw the screen! And I have a very powerful machine...
Anyway, if I can help in something, or support the development in some 
way - a domain? space in vps? Don't know... - I'm right here.

Thanks to all you developers!



Iain Ross wrote:

**Comment by iainross** [comment]
The update to the pop out windows (including the SPanel) is now happening and when it appears you'll be able to have multiple SPanels so you can have one with travel history in one corner and one with the scan data somewhere else, as suits.

**Comment by andreaspada** [comment]
Amazing! Thank you so much!!

Enviado do meu iPhone
