### ISSUE TITLE
Export routes and expeditions

### ISSUE THREAD

**Issue by tonkepen100** [EDDiscovery/EDDiscovery#640]
It would be sensational that in the section of routes and expeditions could be exported routes that we created, so also in the same section would be really good that in the end add up the total of the route.

I leave photo

![captura1](https://cloud.githubusercontent.com/assets/4571086/21409605/7be59f32-c7db-11e6-97e1-ec1196c77e28.PNG)

![captura2](https://cloud.githubusercontent.com/assets/4571086/21409614/82bea27c-c7db-11e6-8e75-aae0ba25241f.PNG)

Thank you very much.

**Comment by jthorpe4** [comment]
I also think that would be a cool idea, and a CSV import so we could share routes/.expeds like C3E that I just got back from.   Also I was thinking of adding a waypoint tracker to the trip panel, so that you could pick an expeditions and it would work a little like a sat nav setting the next target as you fly through a waypoint, how many jumps, distance etc......

**Comment by jthorpe4** [comment]
I've added a few extra features to the routing tab hopefully they will be in the next beta, I've added export and import.  The import is the same format as importstars.txt.   One line per system in the order you wish to load them.  And I've added total distance and straight line distance between start and stop.

**Comment by tonkepen100** [comment]
Ohhhhh, awesome, thank you very much.
