### ISSUE TITLE
Window position and layout not saved if it's maximized

### ISSUE THREAD

**Issue by Geobert** [EDDiscovery/EDDiscovery#652]
Each time I launch EDDiscovery, I need to put it on the screen I want it to be and resize all the panels.
It would be a big QOL improvement to save and restore these :)

**Comment by iainross** [comment]
The main form should go back to where it was last closed (assuming that's still a valid position and you've not unplugged a monitor or anything) with panels sized as at last shutdown.  Is that not working for you?

I've only got the one screen, mind, so if it's a multi-monitor issue then you might be seeing something I can't...

**Comment by Geobert** [comment]
Yes, I'm on a multimonitor setup. Do you save negative position? Because on Win, the main screen is starting at (0,0). The screen on the left of the main screen will have negative coordinates.

**Comment by iainross** [comment]
It should cope with -ve left (no -ve top but I'm going to assume you've got them beside each other so that's not an issue).  You're not starting it with the -noreposition flag in the command line?  That will suppress the put-it-back-where-it-was behaviour.

If you're not can you try putting it somewhere on your main screen other than the default, close it and see if it reopens there?

**Comment by Geobert** [comment]
Hi again, done some test, I use portable version and no command line option.

The bug happens when I maximise the window. If I size it to match my left screen, it pop here again on next launch with everything in place :) Hope this help.

**Comment by klightspeed** [comment]
I don't think window maximization is supported in EDDiscovery at the moment - I thought the maximize button was disabled, and there is no maximize button when using a borderless window theme.

I'm not sure if Windows stores which monitor the window was maximized on - I don't think we are currently overriding the window maximization state in the start parameters, so that would be getting populated by the OS.

Perhaps we should have a flag saying whether or not the window was maximized, and create the window non-maximized, then maximize it if it was maximized when last closed.

The window location is loaded and saved in screen coordinates, and should handle the left or top monitor not being the primary monitor.

**Comment by Geobert** [comment]
5.2.5.0
If close when maximized, it restores as maximized, but not on the screen I closed it.

Moreover, the sizing of the different panel is not correctly restored

**Comment by iainross** [comment]
Yeah, I did fear that might happen.  It works on one monitor (including panel sizing) - and I've only got one monitor...  Hopefully one of the dev team with more than one can make the necessary further tweaks soon...
