### ISSUE TITLE
Send Commodity Market data to EDDN

### ISSUE THREAD

**Issue by iPeer** [EDDiscovery/EDDiscovery#757]
Would be nice to have it send market data to keep places like EDDB up-to-date with the latest information. EDMC already does this, but EDD and EDMC both conflict with each other. Would be really nice to only need to run one program to track this stuff.

**Comment by phroggster** [comment]
This would be a huge undertaking, and will require your Frontier login information in order to access their (mostly) unsupported API. Not saying that it's impossible, just that it's huge.

Meanwhile, you can set EDMC to upload scans to EDDN and EDSM, and disable sync to EDSM and EDDN in EDDiscovery, and everything works out great (with EDMC also handling several EDSM features that we don't support).

**Comment by finwen** [comment]
We have talked about adding it but it will be lots of work  but it might happen in the future.

**Comment by robbyxp1** [comment]
In the pipeline ;-)

**Comment by robbyxp1** [comment]
Its in 8.0
