### ISSUE TITLE
Crash on initial Load (Portable)

### ISSUE THREAD

**Issue by St3vet** [EDDiscovery/EDDiscovery#786]
EDD fails to load.
I've posted a screen shot of the error on the FDev forum, before I read the error message properly and realised I should do it here.
I've attached the log file.  I've changed the suffix to .txt in order to load it here.

[Trace_20170201145749.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/745246/Trace_20170201145749.0.txt)

I hope you can help.  Thank you.

The reference to "V:\RobertW\EDDiscovery\......" is wrong.  It should be "S:\EDDiscovery.Portable\.........".

**Comment by phroggster** [comment]
>[2017-02-01 14:58:58Z] Exception : database disk image is malformed
>[2017-02-01 14:58:58Z] database disk image is malformed

Best I can offer is to try a checkdisk on your S: drive. To do so:
1. Press WindowKey+E to open an Explorer window.
2. Click on This PC on the left (or My Computer, or Computer, or whatever it may have been renamed to).
3. Right-click on the S: drive at the right, and click Properties.
4. Click the Tools tab, then the Check button.
5. If you get a prompt saying that no check is necessary, click the test to check anyways.

Hopefully, this will find and correct the issue, and you'll be able to run EDDiscovery again. However, I would strongly advise you to migrate to using a new jump drive, as it is likely failing, or was (possibly) unplugged at a very unfortunate time.

**Comment by klightspeed** [comment]
It looks like the systems DB is corrupt.

Please delete `Data\eddsystem.sqlite` and try again.

**Comment by St3vet** [comment]
Thanks for your advice.
I took the easy option first and followed phroggster's advice first.  It worked!!!
So I don't need to delete anything I hope klightspeed.
All my notes etc were there, nothing appears to have suffered.

Thanks again, I'm mightily relieved.

**Comment by phroggster** [comment]
Glad to hear that it resolved your issue!

Assuming that it wasn't an unfortunately-timed unplugging of a jump drive, I would probably go ahead and make a backup of anything on there that's critical. To confirm, the systems database is not critical, and can be recreated as easily as klightspeed's comment suggests, but the user database may contain comments that are not stored elsewhere. I don't know what else is on the drive, but here's your typical "backups are important" line, just in case it hasn't been heard recently. ;-)

**Comment by St3vet** [comment]
Thanks again.   Wise advice.

**Comment by klightspeed** [comment]
In this case, I guess it's not actually a good idea to change the System DB init to attempt to automatically re-create the System DB when this error is encountered.

**Comment by phroggster** [comment]
What are the odds that an fsck/checkdisk is going to resolve the file error? I mean, I type it out often enough, but, realistically? Maybe 50%, tops. System DB is still a large pull, be a good thing to avoid it if at all possible.

We could/should probably figure out a way to catch that exception (maybe a couple others that are from similar circumstances), display an OS-dependent "Here's how to run fsck, but we can't do it for you because you're not root" dialog (is there a website like [portforward.com](https://portforward.com/router.htm) for checkdisk that accepts a path parameter that we could link them to? Maybe add a wiki page and link them to that?). Then fallback that other 75% and just wipe the DB and start fresh. I dunno. ¯\_(ツ)_/¯
