### ISSUE TITLE
Map Proposal: 2 Default zoom levels?

### ISSUE THREAD

**Issue by gregmalcolm** [EDDiscovery/EDDiscovery#82]
One thing I've been thinking about, Rather than have a single zoom setting, we might be better off choosing defaults for the user depending on where they are on the map. When in the bubble I think the user benefits from a reasonably close zoom level where they can see all the neighboring systems in close jump range. When outside we can assume they are exploring, so I'd default to being zoomed out much further (maybe showing 33%-50% of the map?). It might be better to just have 2 carefully chosen constants rather than settings if we go down this path.

Thoughts?

/cc @iainross

**Comment by iainross** [comment]
I'm mostly pulling up the map to see how my line around the edge of the galaxy is growing and I want it zoomed all the way out (at least at the minute) - so any default zoomed in more than that would already be a minor irritation for me.  

Your idea might work for a lot of people though, possibly worth having a play to see how it turns out and if it seems good then enable it with an 'Auto' zoom setting but leave the option to over-ride with the current setting as well?

**Comment by gregmalcolm** [comment]
Yeah, it's true, when exploring you probavly want to start with the whole map and zoom in. So I guess that would either be zoomed to the whole map is half the window (ensuring you can see it everywhere), or do some math so it starts zoomed just enough to show the whole map exactly.

Side thoughr: a half second transition animation from zoomed in all the way to the desired zoom out would look cool.

**Comment by Red13x3** [comment]
Had a look at the latest released version last night and wanted to give feedback:

1. Generally working well. Love the lines feature. Rotation works well, except after translation. 

2. Translation still seems dodgy. For a start, it seems the movement is the reversed of my mouse movement. When I right click-drag down, the map ends up moving up. Also, the screen doesn't update while I scroll - only redraws once I let go of the mouse. Finally, the centre of rotation (COR) moves which is not what happens in Elite. The COR should remain on the currently highlighted star system. 

--
Red_XIII

**Comment by robbyxp1** [comment]
CLosed. discussion
