### ISSUE TITLE
Screenshots strangely stopped working after update - BUG

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#917]
I just compiled the last git commitment and when I take a screenshots the following message appear:

`Error in executing image conversion, try another screenshot, check output path settings. (Exception Object reference not set to an instance of an object.)`

No setting were modified. I use the Commander/System organization. Tried also with other commanders, and others organization =, but all of them gave me such message.

How could be trace the problem?

**Comment by andreaspada** [comment]
Got this on the trace.log:

`[2017-03-21 14:52:07Z] Trace:    at EDDiscovery2.ImageHandler.ImageConverter.GetOutputSubFolder() in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 828

[2017-03-21 14:52:07Z]    at EDDiscovery2.ImageHandler.ImageConverter.Convert() in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 664

[2017-03-21 14:52:07Z]    at EDDiscovery2.ImageHandler.ScreenshotDirectoryWatcher.ProcessScreenshot(String filename, String sysname, JournalScreenshot ss, Int32 cmdrid, ImageConverter cp) in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 592`

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/ImageHandler.cs#L828

This suggests that something is wrong with the commander list.

**Comment by andreaspada** [comment]
Already thought about, but I noticed that the 6.1.0 build, with exactly the same configuration and Data folder, works ok. Yes, the 6.1.0 builds do not have the CMDR organization option, but the last build do present the same bug with all the options.

Although, my local build - when I wrote the first CMDR/System tweak - works as expected... as I said, same Data folder.

**Comment by klightspeed** [comment]
Dereferencing the value returned from `EDDConfig.Instance.Commander(CommanderID)`, or having a null OutputFolder, are the only places on that line where a null reference exception could occur.  This means that either `EDDConfig.Instance.Commander(CommanderID)` returned null, which since CommanderID must be positive would mean that none of the entries in the commander list have the referenced commander ID, or that retrieving the output folder text from the UI somehow returned null.

That commander ID is set at https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/ImageHandler.cs#L590, https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/ImageHandler.cs#L655 and/or https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/ImageHandler.cs#L660

The only things I can think of are:
* The output folder UI field is returning null - though if this were the case, it'd be a problem for any subfolder choice;
* There is no commander 0, and the commander ID is uninitialized; or
* The commander list was empty at the point where the screenshot was taken.
