### ISSUE TITLE
Feature request: "Terraformable" icon on the scan view

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#962]
With the new changes in 2.3 to the exploration scan value, terraformable planets are worth a lot more than before.

Would it be possible to have terraformable planets stand out slightly on the scan window? Much like you are showing a small hexagon with a + for planets with materials, perhaps a small T on the planet?

**Comment by robbyxp1** [comment]
Its possible.. have to test it grahically.

**Comment by mwerle** [comment]
Along with this can we get "volcanism" (and any other interesting) icons for overlay?

**Comment by robbyxp1** [comment]
Add to this someone asked for habital zone

**Comment by wokket** [comment]
Habitat Zone markings are in #1185, I'll deal with them there.

I have a PoC for a terraformable overlay now, just looking for a validly licenced icon.  Is there a standard icon suite already in use in the app to simplify licencing?

What's everyone's thinking on the Volcanism thing?  I can see the value in ID'ing terraformables from a credit/hr perspective but more detailed info than that is getting into low/slow exploration where I don't think rapid ID is as handy??  Happy to be convinced otherwise.

**Comment by phroggster** [comment]
Volcanism labelling and/or iconography would be a stellar thing to include alongside terraformable labelling and/or iconography, since they would likely interact and be very similar features.

As for imagery licensing, there's not many choices. I believe that so far all icons have been hand drawn by a member of the team, and released under the Apache 2.0 (or compatible) licensing. It's technically possible to use something slightly more permissive, but no record of that currently exists in our LICENSE.md file, which is where that would need to be documented. Of course, a trivial subset of "our" actual code is distributed under an alternate license, but it is clearly marked as such in the individual file preamble.

**Comment by wokket** [comment]
Thanks phroggster.

I agree the two features are very similar, and other than the issues of overlay placement/finding an icon pretty simple to implement.... I'm trying to work out _why_ you want to know about volcanism in the system at first glance.

I've grabbed the Transformer image from [here](http://brankic1979.com/icons/) for the moment, please let me know if that isn't suitable.

I should have a PR available very shortly.

**Comment by phroggster** [comment]
The *why* is simple: I frequently find myself in desperate need of a surface POI to sacrifice a virgin SRV to in order to please the goods before my next jump. Don't you? 👾 

In all seriousness, it may mean looking closer at a surface merely as a means to get away from jump, honk, scan, jump, honk, scan, ad infitum.

**Comment by phroggster** [comment]
Actually, I retract my prior edit: the transformer logo would ***NOT*** be ok to use, despite the artist's explicit consent, as that is very likely both copyrighted and trademarked in numerous jurisdictions. A more generic icon of some sort would be better suited.

**Comment by mwerle** [comment]
We currently don't get additional planetary items notified in the logs, but would it be possible in future to use player-generated data for overlays as well?  Such as planetary bases, braintrees, barnacles, ruins, etc.  Similar reasoning as phroggster's - encourage planetary exploration rather than just jump-honk.

Also, for terraformable, I would suggest a leaf icon (eg https://www.123rf.com/photo_26265311_set-with-green-leaf-icons-in-round-frame.html)

**Comment by radioactiv** [comment]
I have a suggestion that would work well with this change.  Add a setting option for indicating scan value if it's above a user set amount.  Having a star next to things that are 20k+ or 200k+ would be nice.

**Comment by wokket** [comment]
The merged patch under #1347 included an indicator icon for bodies estimated to be worth over 50k.  Does that help you?

**Comment by radioactiv** [comment]
It helps, but I was thinking an arbitrary limit would be more helpful for people.
A new player might want to see 2k+ highlighted, but a more senior player wouldn't do more than honk the system if there wasn't a 200k+.

**Comment by klightspeed** [comment]
The only way to tell if a system has valuable planets is either to scan them or retrieve scans somebody else has taken and submitted.

**Comment by radioactiv** [comment]
EDSM provides that information...

**Comment by klightspeed** [comment]
> EDSM provides that information...

That is where "retrieve scans somebody else has taken and submitted." comes from.

**Comment by radioactiv** [comment]
To clarify, if I see that there are planets that aren't visible on EDDiscovery, or on EDSM, and I check the system map and see that they look valuable [2k+] I'll go out of my way to scan them.  

How does the fact that the data comes from EDSM affect this?

**Comment by klightspeed** [comment]
I'll re-word: EDDiscovery can only notify you about planets that either you yourself have scanned, or those for which EDSM has received a scan from another player.

If you are going where none have gone before, or the bodies were last scanned before Elite Dangerous 2.2 was released, your only data source is the Elite Dangerous system map, and neither EDDiscovery nor EDSM will have any data until after the bodies have been scanned.

**Comment by radioactiv** [comment]
Yes, I understand that, but if it has been seen before and logged giving a player a better indication of the systems value is useful.  

Just because the system has been "discovered" in the game doesn't mean that it still won't show for them as unknown.  My request relates to exploration within "The Bubble", not out in the dark.

**Comment by wokket** [comment]
Can I suggest you give the new indicator a go?  The value of 50k was chosen to highlight MR, TF, WW, ELW etc.

If you're chasing 200k+ it's pretty obvious you should just ignore the MR in tight to the star, the rest are good to go.

If you're chasing 2k+ you should scan everything in the system.

I understand that a user-configurable value would be better, but I'm not convinced the extra utility is worth the effort (cluttering the settings screen, input validation, load/save, default values etc).
