### ISSUE TITLE
Display potential habitable zone on Scan panel

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#977]
Suggestion;
Some time back the code to estimate the habitable zone was added (presume it's still there).  Could this be displayed in the system panel, perhaps as a green bar or something, and then have the planets displayed relative to that.  So say the zone is 300 to 2000ls, and planet 1 is at 150ls, it shows to the left of the bar.  Planet 2 at 500ls is on the bar and planet 5 at 2500ls is to the right of the bar.

As bodies are scanned and confirmed (or not) terraformable, then the graphic could be adjusted.

As a secondary aspect to this, perhaps it can be an option to display the bodies in relative scale from the star too.  This might only work if you pop the panel out on a 2nd screen l do.

**Comment by ZexMaxwell001** [comment]
I like first idea. It's nice to know visually or textually where the Goldilocks zone is. It helps time pressed explorers who only want to bucky ball. Sadly, on my second screen, it's filled with edd, discord and other stuff.

**Comment by RedfoxCh** [comment]
Displaying the hab-zone in the scan panel would be great. That would remove the need to alt-tab to edd and click on the star to get it displayed.

Visualisong the planets along a 'measuring tape' would really look neat. That said, I can't quite see any actual added value to that. The distance to the star is available on the System Map even before one scans the planet, so no efficiency or information gains there. Maybe I'm missing something?

**Comment by Disorganise** [comment]
Regards the scaling - really just a cosmetic guide to just how big a solar system is, though I do tend to forget the raw numbers from sys map so having them available outside would be useful.  It could also be done with a rough 'SC time' required to get there which might be of value.  It only  really works in the bubble since you need to have scanned the bods in the first place.

**Comment by RedfoxCh** [comment]
@Disorganise Thanks for elaborating - yeah, getting a feeling for the distances would really be a nice idea. Playing devil's advocate here there are the following things to consider: This wouldn't work in the bubble, as ED won't let us scan 'commonly known' bodies there, due to which we'll not have most of those in-system distances (except someone enters them manually). Additionally, but less importantly, the distances are obviously only valid from them main star. As soon as you move from there they become redundant for the rest of your cruising within that system.
Have you seen that Orrery mockup someone did a few years back? That would probably suit your need - besides being absolutely awesome :-D
Of course I had to look it up now ;-) http://i.imgur.com/gDU5nwJ.png

**Comment by robbyxp1** [comment]
Incoming on 8.3
