### ISSUE TITLE
Enhancement to Synthesis panel

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#985]
The synthesis panel is good, but I was looking for a slightly different "tool".

As you scan planets in a system, it'll gradually show you what can be created using the materials you've found just in that system.

So you can then tell what can be synthesised using *just* the planets in that system, regardless of what materials you might already have.

Hope I've explained that okay!!

**Comment by tivec** [comment]
I like this idea. It can also be expanded on, showing the planet in the system that have the best concentration of the given material.

For instance, if I choose that I want FSD Standard, it'd show me I need additional Niobium. The notes column could then show the planet with the highest concentration of Niobium in the system.

**Comment by robbyxp1** [comment]
Nice idea.. No idea when and who to do it.

**Comment by robbyxp1** [comment]
I think tivec comment is most doable.. search the scan list for best planet.  it will only be ones we have scan data for, not some bit pull of data from EDSM.

**Comment by mpfj** [comment]
Yes ... you should only use what you've scanned.

Maybe the Synthesis panel could simply highlight the "Upgrade/Mat" item if it's ingredients have been found in the system.

**Comment by Uriei** [comment]
I would like to ask for a better filtering for the Synthesis panel, something like the Engineering one has, filtering by tiers and so, right now the "Travel" filter is almost useless because it includes all synthesis ingame but ammo for weapons, a dropdown menu with checkboxes to mark which ones I would like to show would be really great as a simple filtering method.
